//! Platform-neutral viewer-side input capture reducer.
//!
//! Emergency release chord: **Ctrl+Alt+Shift+Escape**. It is recognized locally before normal
//! forwarding, releases all remote keys and mouse buttons, and switches to view-only mode. The
//! Escape press itself never reaches the remote host. The viewer application should keep this
//! reducer active for the lifetime of the window so the chord remains available while capturing.

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt;

use racc_proto::{InputEvent, InputEventKind};
use racc_topology::{
    normalize_pointer, CoordinateError, NormalizedPointer, PointerPolicy, RenderedRect,
};

use crate::SUPPORTED_HID_USAGES;

/// Maximum number of typed events one reducer action can return.
pub const MAX_VIEWER_EVENTS_PER_ACTION: usize = 512;
const MAX_TRACKED_KEYS: usize = 256;
const MAX_MOUSE_BUTTON: u8 = 5;
const MODIFIER_SHIFT: u8 = 0x01;
const MODIFIER_CONTROL: u8 = 0x02;
const MODIFIER_ALT: u8 = 0x04;
const RELEASE_CHORD_MASK: u8 = MODIFIER_SHIFT | MODIFIER_CONTROL | MODIFIER_ALT;
const HID_ESCAPE: u16 = 0x29;
const HID_F12: u16 = 0x45;

/// Locally consumed release chord selected in Settings.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum ReleaseChord {
    /// Ctrl+Alt+Shift+Escape (also remains the built-in emergency fallback).
    #[default]
    CtrlAltShiftEscape,
    /// Ctrl+Alt+Shift+F12.
    CtrlAltShiftF12,
}

impl ReleaseChord {
    fn hid_usage(self) -> u16 {
        match self {
            Self::CtrlAltShiftEscape => HID_ESCAPE,
            Self::CtrlAltShiftF12 => HID_F12,
        }
    }
}

/// Viewer control mode for a selected remote display.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum ViewerControlMode {
    /// Watch video without forwarding keyboard or mouse input.
    #[default]
    ViewOnly,
    /// Capture keyboard and pointer input while focused and visible.
    RemoteDesktop,
}

/// Typed action for pointer, button, wheel, and relative-motion input.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ViewerMouseInput {
    /// Pointer position in viewer device pixels and the actual rendered video rectangle.
    Move {
        /// Horizontal viewer device-pixel coordinate.
        px: i64,
        /// Vertical viewer device-pixel coordinate.
        py: i64,
        /// Letterboxed or pillarboxed video rectangle in viewer device pixels.
        rendered_rect: RenderedRect,
    },
    /// Mouse button transition, with current pointer position for accurate click placement.
    Button {
        /// Protocol button number: 1 left, 2 right, 3 middle, 4 back, 5 forward.
        button: u8,
        /// True for down, false for up.
        pressed: bool,
        /// Horizontal viewer device-pixel coordinate.
        px: i64,
        /// Vertical viewer device-pixel coordinate.
        py: i64,
        /// Actual rendered video rectangle in viewer device pixels.
        rendered_rect: RenderedRect,
    },
    /// Wheel movement in units of 1/120 notch.
    Wheel {
        /// Horizontal wheel units.
        dx: i16,
        /// Vertical wheel units.
        dy: i16,
    },
    /// Raw relative movement in device units.
    Relative {
        /// Horizontal delta.
        dx: i16,
        /// Vertical delta.
        dy: i16,
    },
}

/// Typed viewer-side result event.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ViewerInputEvent {
    /// Validated event to send through the control channel.
    Input(InputEvent),
    /// UI state for the visible keyboard-and-mouse capture indicator.
    CaptureChanged {
        /// Whether remote keyboard and mouse capture is active.
        captured: bool,
    },
    /// The local emergency release chord was consumed.
    ReleaseChordTriggered,
}

/// Bounded collection of viewer events generated by one reducer action.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ViewerInputEvents {
    events: Vec<ViewerInputEvent>,
}

impl ViewerInputEvents {
    /// Returns generated events in the order they should be applied or sent.
    pub fn as_slice(&self) -> &[ViewerInputEvent] {
        &self.events
    }

    /// Returns the number of generated events.
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// Returns whether the action generated no events.
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Consumes this collection and returns its bounded event vector.
    pub fn into_vec(self) -> Vec<ViewerInputEvent> {
        self.events
    }

    fn push(&mut self, event: ViewerInputEvent) -> Result<(), ViewerInputError> {
        if self.events.len() >= MAX_VIEWER_EVENTS_PER_ACTION {
            return Err(ViewerInputError::OutputLimitExceeded);
        }
        self.events.push(event);
        Ok(())
    }

    fn input(&mut self, input: InputEvent) -> Result<(), ViewerInputError> {
        self.push(ViewerInputEvent::Input(input))
    }
}

/// Typed error from viewer input validation or pointer normalization.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ViewerInputError {
    /// Display id zero is reserved and cannot be selected for remote input.
    InvalidDisplayId,
    /// A physical key is not a supported USB HID keyboard-page usage.
    UnsupportedHidUsage(u16),
    /// Modifier bits exceed Shift, Control, Alt, and Meta.
    InvalidModifiers(u8),
    /// A mouse button number is outside the protocol's 1 through 5 range.
    InvalidMouseButton(u8),
    /// More unique keys are held than the reducer's fixed safety bound.
    TooManyHeldKeys,
    /// A topology coordinate was invalid or overflowed during normalization.
    Coordinate(CoordinateError),
    /// Internal fixed output capacity was exceeded.
    OutputLimitExceeded,
}

impl fmt::Display for ViewerInputError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidDisplayId => formatter.write_str("display id zero is reserved"),
            Self::UnsupportedHidUsage(usage) => {
                write!(formatter, "unsupported HID keyboard usage 0x{usage:04x}")
            }
            Self::InvalidModifiers(modifiers) => {
                write!(formatter, "invalid modifier bits 0x{modifiers:02x}")
            }
            Self::InvalidMouseButton(button) => write!(formatter, "invalid mouse button {button}"),
            Self::TooManyHeldKeys => formatter.write_str("viewer held-key safety bound exceeded"),
            Self::Coordinate(error) => write!(formatter, "pointer normalization failed: {error}"),
            Self::OutputLimitExceeded => formatter.write_str("viewer event output bound exceeded"),
        }
    }
}

impl Error for ViewerInputError {}

/// State reducer for viewer-side keyboard and pointer capture.
///
/// The caller supplies physical USB HID usages and OS-independent focus/session changes. This
/// reducer owns held-key/button tracking, pointer letterbox handling, modifier validation, and the
/// local release chord. It never logs input content.
pub struct ViewerInputReducer {
    epoch: u16,
    display_id: u32,
    mode: ViewerControlMode,
    focused: bool,
    visible: bool,
    paused: bool,
    connected: bool,
    release_chord: ReleaseChord,
    held_keys: BTreeSet<u16>,
    held_buttons: BTreeSet<u8>,
}

impl ViewerInputReducer {
    /// Creates an inactive reducer for a selected stream target.
    pub fn new(epoch: u16, display_id: u32) -> Result<Self, ViewerInputError> {
        if display_id == 0 {
            return Err(ViewerInputError::InvalidDisplayId);
        }
        Ok(Self {
            epoch,
            display_id,
            mode: ViewerControlMode::ViewOnly,
            focused: false,
            visible: true,
            paused: false,
            connected: false,
            release_chord: ReleaseChord::default(),
            held_keys: BTreeSet::new(),
            held_buttons: BTreeSet::new(),
        })
    }

    /// Returns whether remote keyboard and pointer capture is currently active.
    pub fn is_capturing(&self) -> bool {
        self.mode == ViewerControlMode::RemoteDesktop
            && self.focused
            && self.visible
            && !self.paused
            && self.connected
    }

    /// Changes view-only or remote desktop mode and emits state/release events as needed.
    pub fn set_mode(
        &mut self,
        mode: ViewerControlMode,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        let was_capturing = self.is_capturing();
        self.mode = mode;
        self.finish_state_change(was_capturing)
    }

    /// Updates whether the viewer window owns keyboard focus.
    pub fn set_focused(&mut self, focused: bool) -> Result<ViewerInputEvents, ViewerInputError> {
        let was_capturing = self.is_capturing();
        self.focused = focused;
        self.finish_state_change(was_capturing)
    }

    /// Updates window visibility; hiding releases held remote input.
    pub fn set_visible(&mut self, visible: bool) -> Result<ViewerInputEvents, ViewerInputError> {
        let was_capturing = self.is_capturing();
        self.visible = visible;
        self.finish_state_change(was_capturing)
    }

    /// Updates pause state; pausing releases held remote input.
    pub fn set_paused(&mut self, paused: bool) -> Result<ViewerInputEvents, ViewerInputError> {
        let was_capturing = self.is_capturing();
        self.paused = paused;
        self.finish_state_change(was_capturing)
    }

    /// Updates connection state; disconnecting releases held remote input.
    pub fn set_connected(
        &mut self,
        connected: bool,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        let was_capturing = self.is_capturing();
        self.connected = connected;
        self.finish_state_change(was_capturing)
    }

    /// Changes the preferred release chord after releasing held input.
    ///
    /// Ctrl+Alt+Shift+Escape remains active as an emergency fallback for every selection.
    pub fn set_release_chord(
        &mut self,
        release_chord: ReleaseChord,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        let mut events = ViewerInputEvents::default();
        if self.release_chord != release_chord {
            self.release_all_into(&mut events)?;
            self.release_chord = release_chord;
        }
        Ok(events)
    }

    /// Switches the stream target and epoch after releasing all remote-held input.
    pub fn set_stream_target(
        &mut self,
        epoch: u16,
        display_id: u32,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        if display_id == 0 {
            return Err(ViewerInputError::InvalidDisplayId);
        }
        let mut events = ViewerInputEvents::default();
        self.release_all_into(&mut events)?;
        self.epoch = epoch;
        self.display_id = display_id;
        Ok(events)
    }

    /// Reduces one physical key event. The release chord is recognized before capture gating.
    pub fn key_event(
        &mut self,
        hid_usage: u16,
        pressed: bool,
        modifiers: u8,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        if modifiers & !0x0f != 0 {
            return Err(ViewerInputError::InvalidModifiers(modifiers));
        }
        let mut events = ViewerInputEvents::default();
        let release_key = hid_usage == HID_ESCAPE || hid_usage == self.release_chord.hid_usage();
        if pressed && release_key && modifiers == RELEASE_CHORD_MASK {
            self.release_all_into(&mut events)?;
            self.mode = ViewerControlMode::ViewOnly;
            events.push(ViewerInputEvent::ReleaseChordTriggered)?;
            events.push(ViewerInputEvent::CaptureChanged { captured: false })?;
            return Ok(events);
        }
        if !self.is_capturing() {
            return Ok(events);
        }
        if !SUPPORTED_HID_USAGES
            .iter()
            .any(|(supported, _)| *supported == hid_usage)
        {
            return Err(ViewerInputError::UnsupportedHidUsage(hid_usage));
        }
        if pressed {
            if self.held_keys.contains(&hid_usage) {
                return Ok(events);
            }
            if self.held_keys.len() >= MAX_TRACKED_KEYS {
                return Err(ViewerInputError::TooManyHeldKeys);
            }
        } else if !self.held_keys.contains(&hid_usage) {
            return Ok(events);
        }
        events.input(InputEvent {
            epoch: self.epoch,
            display_id: self.display_id,
            event: InputEventKind::Key {
                hid_usage,
                pressed,
                modifiers,
            },
        })?;
        if pressed {
            self.held_keys.insert(hid_usage);
        } else {
            self.held_keys.remove(&hid_usage);
        }
        Ok(events)
    }

    /// Reduces mouse movement and button/wheel events. Pointer normalization uses the actual
    /// rendered video rectangle, rejecting outside points during hover and clamping during drag.
    pub fn mouse_event(
        &mut self,
        mouse: ViewerMouseInput,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        let mut events = ViewerInputEvents::default();
        if !self.is_capturing() {
            return Ok(events);
        }
        match mouse {
            ViewerMouseInput::Move {
                px,
                py,
                rendered_rect,
            } => {
                if let Some(pointer) =
                    self.normalize(px, py, rendered_rect, self.pointer_policy())?
                {
                    self.push_pointer(&mut events, pointer)?;
                }
            }
            ViewerMouseInput::Button {
                button,
                pressed,
                px,
                py,
                rendered_rect,
            } => {
                if !(1..=MAX_MOUSE_BUTTON).contains(&button) {
                    return Err(ViewerInputError::InvalidMouseButton(button));
                }
                if pressed == self.held_buttons.contains(&button) {
                    return Ok(events);
                }
                let policy = if self.held_buttons.is_empty() {
                    PointerPolicy::Reject
                } else {
                    PointerPolicy::Clamp
                };
                let Some(pointer) = self.normalize(px, py, rendered_rect, policy)? else {
                    return Ok(events);
                };
                self.push_pointer(&mut events, pointer)?;
                events.input(InputEvent {
                    epoch: self.epoch,
                    display_id: self.display_id,
                    event: InputEventKind::MouseButton { button, pressed },
                })?;
                if pressed {
                    self.held_buttons.insert(button);
                } else {
                    self.held_buttons.remove(&button);
                }
            }
            ViewerMouseInput::Wheel { dx, dy } => {
                events.input(InputEvent {
                    epoch: self.epoch,
                    display_id: self.display_id,
                    event: InputEventKind::Wheel { dx, dy },
                })?;
            }
            ViewerMouseInput::Relative { dx, dy } => {
                events.input(InputEvent {
                    epoch: self.epoch,
                    display_id: self.display_id,
                    event: InputEventKind::MouseMoveRel { dx, dy },
                })?;
            }
        }
        Ok(events)
    }

    fn pointer_policy(&self) -> PointerPolicy {
        if self.held_buttons.is_empty() {
            PointerPolicy::Reject
        } else {
            PointerPolicy::Clamp
        }
    }

    fn normalize(
        &self,
        px: i64,
        py: i64,
        rect: RenderedRect,
        policy: PointerPolicy,
    ) -> Result<Option<NormalizedPointer>, ViewerInputError> {
        normalize_pointer(rect, px, py, policy).map_err(ViewerInputError::Coordinate)
    }

    fn push_pointer(
        &self,
        events: &mut ViewerInputEvents,
        pointer: NormalizedPointer,
    ) -> Result<(), ViewerInputError> {
        events.input(InputEvent {
            epoch: self.epoch,
            display_id: self.display_id,
            event: InputEventKind::MouseMoveAbs {
                u: pointer.u,
                v: pointer.v,
            },
        })
    }

    fn finish_state_change(
        &mut self,
        was_capturing: bool,
    ) -> Result<ViewerInputEvents, ViewerInputError> {
        let now_capturing = self.is_capturing();
        let mut events = ViewerInputEvents::default();
        if was_capturing && !now_capturing {
            self.release_all_into(&mut events)?;
        }
        if was_capturing != now_capturing {
            events.push(ViewerInputEvent::CaptureChanged {
                captured: now_capturing,
            })?;
        }
        Ok(events)
    }

    fn release_all_into(&mut self, events: &mut ViewerInputEvents) -> Result<(), ViewerInputError> {
        let mut keys: Vec<u16> = self.held_keys.iter().copied().collect();
        keys.sort_by_key(|usage| is_modifier(*usage));
        for hid_usage in keys {
            events.input(InputEvent {
                epoch: self.epoch,
                display_id: self.display_id,
                event: InputEventKind::Key {
                    hid_usage,
                    pressed: false,
                    modifiers: 0,
                },
            })?;
        }
        self.held_keys.clear();

        for button in self.held_buttons.iter().copied() {
            events.input(InputEvent {
                epoch: self.epoch,
                display_id: self.display_id,
                event: InputEventKind::MouseButton {
                    button,
                    pressed: false,
                },
            })?;
        }
        self.held_buttons.clear();
        Ok(())
    }
}

fn is_modifier(hid_usage: u16) -> bool {
    (0xe0..=0xe7).contains(&hid_usage)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn reducer() -> ViewerInputReducer {
        let mut reducer = ViewerInputReducer::new(9, 42).expect("valid display");
        reducer.set_connected(true).expect("connection");
        reducer.set_focused(true).expect("focus");
        reducer
            .set_mode(ViewerControlMode::RemoteDesktop)
            .expect("remote mode");
        reducer
    }

    fn rect() -> RenderedRect {
        RenderedRect::new(100, 50, 400, 200).expect("valid render rect")
    }

    fn input(events: &ViewerInputEvents) -> Vec<InputEvent> {
        events
            .as_slice()
            .iter()
            .filter_map(|event| match event {
                ViewerInputEvent::Input(input) => Some(*input),
                _ => None,
            })
            .collect()
    }

    #[test]
    fn hover_rejects_points_outside_actual_rendered_video_rectangle() {
        let mut reducer = reducer();
        let outside = reducer
            .mouse_event(ViewerMouseInput::Move {
                px: 99,
                py: 100,
                rendered_rect: rect(),
            })
            .expect("outside hover is ignored");
        assert!(outside.is_empty());

        let inside = reducer
            .mouse_event(ViewerMouseInput::Move {
                px: 300,
                py: 150,
                rendered_rect: rect(),
            })
            .expect("inside hover");
        assert_eq!(
            input(&inside),
            [InputEvent {
                epoch: 9,
                display_id: 42,
                event: InputEventKind::MouseMoveAbs {
                    u: 32_768,
                    v: 32_768,
                },
            }]
        );
    }

    #[test]
    fn pointer_clamps_to_video_edge_while_a_button_is_held() {
        let mut reducer = reducer();
        let down = reducer
            .mouse_event(ViewerMouseInput::Button {
                button: 1,
                pressed: true,
                px: 200,
                py: 100,
                rendered_rect: rect(),
            })
            .expect("left down");
        assert_eq!(input(&down).len(), 2);

        let dragged = reducer
            .mouse_event(ViewerMouseInput::Move {
                px: 700,
                py: 100,
                rendered_rect: rect(),
            })
            .expect("drag clamped");
        assert_eq!(
            input(&dragged),
            [InputEvent {
                epoch: 9,
                display_id: 42,
                event: InputEventKind::MouseMoveAbs {
                    u: u16::MAX,
                    v: 16_384,
                },
            }]
        );
    }

    #[test]
    fn button_press_outside_video_is_rejected_and_not_tracked() {
        let mut reducer = reducer();
        let events = reducer
            .mouse_event(ViewerMouseInput::Button {
                button: 1,
                pressed: true,
                px: 501,
                py: 100,
                rendered_rect: rect(),
            })
            .expect("outside press ignored");
        assert!(events.is_empty());
    }

    #[test]
    fn state_changes_release_all_held_keys_and_buttons() {
        for change in 0..4 {
            let mut reducer = reducer();
            reducer.key_event(0x04, true, 0).expect("key down");
            reducer
                .mouse_event(ViewerMouseInput::Button {
                    button: 1,
                    pressed: true,
                    px: 200,
                    py: 100,
                    rendered_rect: rect(),
                })
                .expect("button down");
            let events = match change {
                0 => reducer.set_focused(false),
                1 => reducer.set_visible(false),
                2 => reducer.set_paused(true),
                _ => reducer.set_connected(false),
            }
            .expect("state change");
            let input_events = input(&events);
            assert!(input_events.iter().any(|event| matches!(
                event.event,
                InputEventKind::Key {
                    hid_usage: 0x04,
                    pressed: false,
                    ..
                }
            )));
            assert!(input_events.iter().any(|event| matches!(
                event.event,
                InputEventKind::MouseButton {
                    button: 1,
                    pressed: false,
                }
            )));
            assert!(events
                .as_slice()
                .contains(&ViewerInputEvent::CaptureChanged { captured: false }));
            assert!(!reducer.is_capturing());
        }
    }

    #[test]
    fn configured_f12_chord_is_local_and_escape_remains_available() {
        let mut reducer = reducer();
        reducer
            .set_release_chord(ReleaseChord::CtrlAltShiftF12)
            .expect("set configured chord");
        reducer.key_event(0x04, true, 0).expect("key down");

        let custom = reducer
            .key_event(HID_F12, true, RELEASE_CHORD_MASK)
            .expect("configured release chord");
        assert!(custom
            .as_slice()
            .contains(&ViewerInputEvent::ReleaseChordTriggered));
        assert!(!input(&custom).iter().any(|event| matches!(
            event.event,
            InputEventKind::Key {
                hid_usage: HID_F12,
                pressed: true,
                ..
            }
        )));
        assert!(input(&custom).iter().any(|event| matches!(
            event.event,
            InputEventKind::Key {
                hid_usage: 0x04,
                pressed: false,
                ..
            }
        )));
        assert!(!reducer.is_capturing());

        let fallback = reducer
            .key_event(HID_ESCAPE, true, RELEASE_CHORD_MASK)
            .expect("built-in fallback remains active");
        assert!(fallback
            .as_slice()
            .contains(&ViewerInputEvent::ReleaseChordTriggered));
    }

    #[test]
    fn changing_release_chord_releases_held_input_without_exiting_capture() {
        let mut reducer = reducer();
        reducer.key_event(0x04, true, 0).expect("key down");
        let events = reducer
            .set_release_chord(ReleaseChord::CtrlAltShiftF12)
            .expect("change release chord");
        assert!(input(&events).iter().any(|event| matches!(
            event.event,
            InputEventKind::Key {
                hid_usage: 0x04,
                pressed: false,
                ..
            }
        )));
        assert!(reducer.is_capturing());
    }

    #[test]
    fn release_chord_is_local_releases_keys_and_buttons_and_exits_capture() {
        let mut reducer = reducer();
        reducer.key_event(0xe0, true, 0x02).expect("control down");
        reducer.key_event(0xe2, true, 0x06).expect("alt down");
        reducer.key_event(0xe1, true, 0x07).expect("shift down");
        reducer
            .mouse_event(ViewerMouseInput::Button {
                button: 1,
                pressed: true,
                px: 200,
                py: 100,
                rendered_rect: rect(),
            })
            .expect("button down");

        let chord = reducer
            .key_event(HID_ESCAPE, true, RELEASE_CHORD_MASK)
            .expect("release chord");
        assert!(chord.len() <= MAX_VIEWER_EVENTS_PER_ACTION);
        assert!(chord
            .as_slice()
            .contains(&ViewerInputEvent::ReleaseChordTriggered));
        assert!(chord
            .as_slice()
            .contains(&ViewerInputEvent::CaptureChanged { captured: false }));
        assert!(!input(&chord).iter().any(|event| matches!(
            event.event,
            InputEventKind::Key {
                hid_usage: HID_ESCAPE,
                pressed: true,
                ..
            }
        )));
        for usage in [0xe0, 0xe1, 0xe2] {
            assert!(input(&chord).iter().any(|event| matches!(
                event.event,
                InputEventKind::Key { hid_usage, pressed: false, .. } if hid_usage == usage
            )));
        }
        assert!(input(&chord).iter().any(|event| matches!(
            event.event,
            InputEventKind::MouseButton {
                button: 1,
                pressed: false
            }
        )));
        assert!(!reducer.is_capturing());
    }

    #[test]
    fn view_only_drops_input_and_invalid_fields_are_rejected() {
        let mut reducer = ViewerInputReducer::new(1, 42).expect("valid display");
        assert!(reducer
            .key_event(0xffff, true, 0)
            .expect("view only")
            .is_empty());
        reducer.set_connected(true).expect("connection");
        reducer.set_focused(true).expect("focus");
        reducer
            .set_mode(ViewerControlMode::RemoteDesktop)
            .expect("capture");
        assert_eq!(
            reducer.key_event(0xffff, true, 0),
            Err(ViewerInputError::UnsupportedHidUsage(0xffff))
        );
        assert_eq!(
            reducer.key_event(0x04, true, 0x10),
            Err(ViewerInputError::InvalidModifiers(0x10))
        );
        assert_eq!(
            reducer.mouse_event(ViewerMouseInput::Button {
                button: 6,
                pressed: true,
                px: 200,
                py: 100,
                rendered_rect: rect(),
            }),
            Err(ViewerInputError::InvalidMouseButton(6))
        );
    }

    #[test]
    fn wheel_and_relative_motion_remain_raw() {
        let mut reducer = reducer();
        assert_eq!(
            input(
                &reducer
                    .mouse_event(ViewerMouseInput::Wheel { dx: 120, dy: -240 })
                    .expect("wheel")
            )[0]
            .event,
            InputEventKind::Wheel { dx: 120, dy: -240 }
        );
        assert_eq!(
            input(
                &reducer
                    .mouse_event(ViewerMouseInput::Relative { dx: -13, dy: 27 })
                    .expect("relative")
            )[0]
            .event,
            InputEventKind::MouseMoveRel { dx: -13, dy: 27 }
        );
    }
}
