# No external dependencies currently need a license allow entry. Add a verified
# permissive license only when a real dependency requires it, with its reason.
# GPL and AGPL are denied by omission from this explicit allowlist.
[advisories]
yanked = "warn"

[licenses]
allow = []
confidence-threshold = 0.93
private = { ignore = true }

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
