//! Pure app state transitions and user-action command generation.

use racc_core::{
    ClipboardStatus, CoreEvent, CoreSnapshot, DeviceId, DeviceSnapshot, QualityPreset,
    SessionEndReason, UiCommand,
};

/// Main shell view visible to the user.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub enum Page {
    /// Connected or selected remote desktop session.
    #[default]
    Session,
    /// Device discovery and hosting overview.
    Home,
    /// Local hosting and quality preferences.
    Settings,
}

/// Session overlay state, rendered above the held or current frame.
#[derive(Clone, Debug, Default, Eq, Hash, PartialEq)]
pub enum SessionOverlay {
    /// No blocking session state.
    #[default]
    None,
    /// The selected device is being contacted.
    Connecting,
    /// A new display stream is being prepared while the prior frame remains visible.
    Switching,
    /// The viewer has paused the stream because the app is hidden.
    Paused,
    /// The viewer is reconnecting after the control connection was lost.
    Reconnecting,
    /// A peer is waiting for approval on the host.
    WaitingForApproval {
        device_id: DeviceId,
        device_name: String,
    },
    /// A stream or command error is being shown.
    Error(String),
}

/// Local action generated by a widget; it contains no widget or toolkit state.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum UserAction {
    /// Show the session page.
    Session,
    /// Show the home page.
    Home,
    /// Show settings.
    Settings,
    /// Rescan the fake core's known devices.
    DiscoverDevices,
    /// Change the quality used for future peer connections.
    SetDefaultQuality(QualityPreset),
    /// Select a device in the rail.
    SelectDevice(DeviceId),
    /// Connect to an available host from Home.
    Connect(DeviceId),
    /// Select a remote display.
    SelectDisplay(racc_core::DisplayId),
    /// Change viewer quality preference.
    SetQuality(QualityPreset),
    /// Show or hide the app window.
    SetVisible(bool),
    /// Enable or disable the combined keyboard and mouse remote desktop mode.
    ToggleRemoteDesktop,
    /// Toggle the keyboard capture mode.
    SetKeyboardCapture(bool),
    /// Toggle mouse capture mode.
    SetMouseCapture(bool),
    /// Disconnect the current session.
    Disconnect,
    /// Turn host mode on or off.
    SetHosting(bool),
    /// Approve an incoming peer.
    ApprovePeer(DeviceId),
    /// Reject an incoming peer.
    RejectPeer(DeviceId),
    /// Remove an approved peer from the allowlist.
    RemovePeer(DeviceId),
    /// Collapse or expand the device sidebar.
    ToggleDeviceSidebar,
    /// Collapse or expand the live telemetry sidebar.
    ToggleTelemetrySidebar,
}

/// State consumed by the widget tree. Widgets only render these values.
#[derive(Clone, Debug)]
pub struct ViewModel {
    /// Latest metadata snapshot from the core.
    pub core: CoreSnapshot,
    /// Current page.
    pub page: Page,
    /// Preferred quality applied when starting a peer session.
    pub default_quality: QualityPreset,
    /// Most recently selected quality preference for the active session.
    pub session_quality: QualityPreset,
    /// Current session overlay.
    pub overlay: SessionOverlay,
    /// Whether keyboard capture is enabled locally.
    pub keyboard_capture: bool,
    /// Whether mouse capture is enabled locally.
    pub mouse_capture: bool,
    /// Whether the device sidebar is collapsed.
    pub device_sidebar_collapsed: bool,
    /// Whether the telemetry sidebar is collapsed.
    pub telemetry_sidebar_collapsed: bool,
    /// Clipboard status label displayed in the sidebar.
    pub clipboard_status: String,
    /// Most recent user-facing notification.
    pub notification: Option<String>,
    /// Last good frame identifier, retained across a stream reset.
    pub held_frame_id: Option<u32>,
    /// Active stream dimensions (stream content, not monitor dimensions).
    pub stream_dimensions: Option<(u32, u32)>,
}

impl ViewModel {
    /// Creates initial app state from a core metadata snapshot.
    pub fn new(core: CoreSnapshot) -> Self {
        let width = u32::from(core.telemetry.host.width);
        let height = u32::from(core.telemetry.host.height);
        let stream_dimensions = (width > 0 && height > 0).then_some((width, height));
        Self {
            core,
            page: Page::Session,
            default_quality: QualityPreset::P720,
            session_quality: QualityPreset::P720,
            overlay: SessionOverlay::None,
            keyboard_capture: false,
            mouse_capture: false,
            device_sidebar_collapsed: false,
            telemetry_sidebar_collapsed: false,
            clipboard_status: "Ready".to_owned(),
            notification: None,
            held_frame_id: None,
            stream_dimensions,
        }
    }

    /// Applies one user action and returns core commands in order.
    pub fn reduce_action(&mut self, action: UserAction) -> Vec<UiCommand> {
        match action {
            UserAction::Session => self.page = Page::Session,
            UserAction::Home => self.page = Page::Home,
            UserAction::Settings => self.page = Page::Settings,
            UserAction::DiscoverDevices => return vec![UiCommand::DiscoverDevices],
            UserAction::SetDefaultQuality(quality) => self.default_quality = quality,
            UserAction::SelectDevice(device_id) => {
                if self.device_online(&device_id) {
                    self.core.selected_device = Some(device_id.clone());
                    self.page = Page::Session;
                    self.overlay = SessionOverlay::Connecting;
                    self.session_quality = self.default_quality;
                    return vec![
                        UiCommand::SelectDevice(device_id.clone()),
                        UiCommand::SetQuality {
                            device_id,
                            quality: self.default_quality,
                        },
                    ];
                }
                return Vec::new();
            }
            UserAction::Connect(device_id) => {
                if self.device_online(&device_id) {
                    self.core.selected_device = Some(device_id.clone());
                    self.page = Page::Session;
                    self.overlay = SessionOverlay::Connecting;
                    self.session_quality = self.default_quality;
                    return vec![
                        UiCommand::Connect(device_id.clone()),
                        UiCommand::SetQuality {
                            device_id,
                            quality: self.default_quality,
                        },
                    ];
                }
                return Vec::new();
            }
            UserAction::SelectDisplay(display_id) => {
                let Some(device_id) = self.core.selected_device.clone() else {
                    return Vec::new();
                };
                if self.display_available(&device_id, display_id) {
                    self.core.selected_display = Some(display_id);
                    self.overlay = SessionOverlay::Switching;
                    return vec![UiCommand::SelectDisplay {
                        device_id,
                        display_id,
                    }];
                }
                return Vec::new();
            }
            UserAction::SetQuality(quality) => {
                let Some(device_id) = self.core.selected_device.clone() else {
                    return Vec::new();
                };
                self.session_quality = quality;
                if self.core.telemetry.session.last_rtt_us.is_some() {
                    self.overlay = SessionOverlay::Switching;
                }
                return vec![UiCommand::SetQuality { device_id, quality }];
            }
            UserAction::SetVisible(visible) => {
                self.core.visible = visible;
                if !visible {
                    self.overlay = SessionOverlay::Paused;
                } else if matches!(&self.overlay, SessionOverlay::Paused) {
                    self.overlay = SessionOverlay::None;
                }
                return vec![UiCommand::SetVisible(visible)];
            }
            UserAction::ToggleRemoteDesktop => {
                let enabled = !(self.keyboard_capture && self.mouse_capture);
                self.keyboard_capture = enabled;
                self.mouse_capture = enabled;
                return vec![
                    UiCommand::ToggleKeyboardCapture(enabled),
                    UiCommand::ToggleMouseCapture(enabled),
                ];
            }
            UserAction::SetKeyboardCapture(enabled) => {
                self.keyboard_capture = enabled;
                return vec![UiCommand::ToggleKeyboardCapture(enabled)];
            }
            UserAction::SetMouseCapture(enabled) => {
                self.mouse_capture = enabled;
                return vec![UiCommand::ToggleMouseCapture(enabled)];
            }
            UserAction::Disconnect => {
                self.keyboard_capture = false;
                self.mouse_capture = false;
                self.overlay = SessionOverlay::Reconnecting;
                return vec![UiCommand::Disconnect];
            }
            UserAction::SetHosting(enabled) => {
                self.core.hosting_enabled = enabled;
                return vec![UiCommand::SetHosting(enabled)];
            }
            UserAction::ApprovePeer(device_id) => return vec![UiCommand::ApprovePeer(device_id)],
            UserAction::RejectPeer(device_id) => return vec![UiCommand::RejectPeer(device_id)],
            UserAction::RemovePeer(device_id) => return vec![UiCommand::RemovePeer(device_id)],
            UserAction::ToggleDeviceSidebar => {
                self.device_sidebar_collapsed = !self.device_sidebar_collapsed;
            }
            UserAction::ToggleTelemetrySidebar => {
                self.telemetry_sidebar_collapsed = !self.telemetry_sidebar_collapsed;
            }
        }
        Vec::new()
    }

    /// Replaces metadata from a fresh core snapshot and refreshes stream dimensions.
    pub fn apply_snapshot(&mut self, snapshot: CoreSnapshot) {
        let width = u32::from(snapshot.telemetry.host.width);
        let height = u32::from(snapshot.telemetry.host.height);
        if snapshot.telemetry.session.last_rtt_us.is_some() && width > 0 && height > 0 {
            self.stream_dimensions = Some((width, height));
        }
        self.core = snapshot;
    }

    /// Applies one metadata event from the core. Video pixels are never consumed here.
    pub fn apply_event(&mut self, event: CoreEvent) {
        match event {
            CoreEvent::DeviceDiscovered(device) => upsert_device(&mut self.core.devices, device),
            CoreEvent::DeviceOffline { device_id } => {
                if let Some(device) = self
                    .core
                    .devices
                    .iter_mut()
                    .find(|device| device.id == device_id)
                {
                    device.online = false;
                }
            }
            CoreEvent::TopologyChanged {
                device_id,
                topology,
            } => {
                let selected_device = self.core.selected_device.as_ref() == Some(&device_id);
                if let Some(device) = self
                    .core
                    .devices
                    .iter_mut()
                    .find(|device| device.id == device_id)
                {
                    device.displays = topology
                        .displays()
                        .iter()
                        .map(racc_core::DisplaySnapshot::from)
                        .collect();
                }
                if selected_device {
                    let current_available = self.core.selected_display.is_some_and(|selected| {
                        self.core
                            .devices
                            .iter()
                            .find(|device| device.id == device_id)
                            .is_some_and(|device| {
                                device
                                    .displays
                                    .iter()
                                    .any(|display| display.id == selected && display.available)
                            })
                    });
                    if !current_available {
                        self.core.selected_display = self
                            .core
                            .devices
                            .iter()
                            .find(|device| device.id == device_id)
                            .and_then(|device| {
                                device
                                    .displays
                                    .iter()
                                    .find(|display| display.available && display.primary)
                                    .or_else(|| {
                                        device.displays.iter().find(|display| display.available)
                                    })
                            })
                            .map(|display| display.id);
                        self.overlay = SessionOverlay::Error(
                            "The selected display is no longer available".to_owned(),
                        );
                        self.held_frame_id = None;
                    }
                }
            }
            CoreEvent::DisplaySelected {
                device_id,
                display_id,
            } => {
                if self.core.selected_device.as_ref() == Some(&device_id) {
                    self.core.selected_display = Some(display_id);
                    self.overlay = SessionOverlay::Switching;
                }
            }
            CoreEvent::StreamStarted {
                device_id,
                display_id,
                width,
                height,
                ..
            } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.core.selected_display = Some(display_id);
                self.stream_dimensions = Some((u32::from(width), u32::from(height)));
            }
            CoreEvent::StreamReset {
                device_id,
                width,
                height,
                ..
            } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.stream_dimensions = Some((u32::from(width), u32::from(height)));
                self.overlay = SessionOverlay::Switching;
            }
            CoreEvent::DecoderReady { device_id } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.overlay = SessionOverlay::None;
                self.held_frame_id = None;
            }
            CoreEvent::ConnectionStatsUpdated(telemetry) => self.core.telemetry = telemetry,
            CoreEvent::InputCaptureChanged { keyboard, mouse } => {
                self.keyboard_capture = keyboard;
                self.mouse_capture = mouse;
            }
            CoreEvent::SessionEnded { device_id, reason } => {
                if device_id
                    .as_ref()
                    .is_some_and(|id| self.core.selected_device.as_ref() != Some(id))
                {
                    return;
                }
                self.overlay = match reason {
                    SessionEndReason::StreamFailure => {
                        SessionOverlay::Error("The remote stream ended unexpectedly".to_owned())
                    }
                    SessionEndReason::Disconnected => SessionOverlay::None,
                    SessionEndReason::RemoteClosed | SessionEndReason::ControlTimeout => {
                        SessionOverlay::Reconnecting
                    }
                };
                self.keyboard_capture = false;
                self.mouse_capture = false;
            }
            CoreEvent::PendingAuthorization {
                device_id,
                device_name,
            } => {
                self.overlay = SessionOverlay::WaitingForApproval {
                    device_id,
                    device_name,
                };
            }
            CoreEvent::ClipboardStatus(status) => self.clipboard_status = clipboard_label(status),
            CoreEvent::Notification(notification) => {
                self.notification =
                    Some(format!("{}: {}", notification.title, notification.message))
            }
            CoreEvent::VideoUnavailable { device_id } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.overlay = SessionOverlay::Error("Video is unavailable".to_owned())
            }
        }
    }

    /// Records the most recent frame metadata without placing frame data on the event bus.
    pub fn record_frame(&mut self, frame_id: u32) {
        if matches!(&self.overlay, SessionOverlay::Switching) {
            self.held_frame_id = self.held_frame_id.or(Some(frame_id));
        }
    }

    fn device_online(&self, id: &DeviceId) -> bool {
        self.core
            .devices
            .iter()
            .any(|device| &device.id == id && device.online && device.host_capable)
    }

    fn display_available(&self, device_id: &DeviceId, display_id: racc_core::DisplayId) -> bool {
        self.core.devices.iter().any(|device| {
            &device.id == device_id
                && device
                    .displays
                    .iter()
                    .any(|display| display.id == display_id && display.available)
        })
    }
}

fn upsert_device(devices: &mut Vec<DeviceSnapshot>, device: DeviceSnapshot) {
    if let Some(existing) = devices.iter_mut().find(|existing| existing.id == device.id) {
        *existing = device;
    } else {
        devices.push(device);
    }
}

fn clipboard_label(status: ClipboardStatus) -> String {
    match status {
        ClipboardStatus::Ready => "Ready".to_owned(),
        ClipboardStatus::Received { sequence } => format!("Received text update #{sequence}"),
        ClipboardStatus::Sent { sequence } => format!("Sent text update #{sequence}"),
        ClipboardStatus::Failed { message } => format!("Clipboard error: {message}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use racc_core::CoreHandle;
    use racc_testkit::FakeCore;

    fn model() -> ViewModel {
        let fake = FakeCore::new(41);
        ViewModel::new(fake.snapshot().expect("fake snapshot"))
    }

    #[test]
    fn selecting_online_device_emits_selection_but_offline_is_ignored() {
        let mut state = model();
        let online = state
            .core
            .devices
            .iter()
            .find(|device| device.online)
            .expect("online device")
            .id
            .clone();
        let offline = state
            .core
            .devices
            .iter()
            .find(|device| !device.online)
            .expect("offline device")
            .id
            .clone();
        assert_eq!(
            state.reduce_action(UserAction::SelectDevice(online.clone())),
            vec![
                UiCommand::SelectDevice(online.clone()),
                UiCommand::SetQuality {
                    device_id: online,
                    quality: QualityPreset::P720,
                },
            ]
        );
        assert!(matches!(&state.overlay, SessionOverlay::Connecting));
        assert!(state
            .reduce_action(UserAction::SelectDevice(offline))
            .is_empty());
    }

    #[test]
    fn home_connect_uses_the_connect_command_for_available_hosts() {
        let mut state = model();
        let online = state
            .core
            .devices
            .iter()
            .find(|device| device.online && device.host_capable)
            .expect("online host")
            .id
            .clone();
        assert_eq!(
            state.reduce_action(UserAction::Connect(online.clone())),
            vec![
                UiCommand::Connect(online.clone()),
                UiCommand::SetQuality {
                    device_id: online.clone(),
                    quality: QualityPreset::P720,
                },
            ]
        );
        assert_eq!(state.core.selected_device, Some(online));
        assert_eq!(state.page, Page::Session);
        assert_eq!(state.overlay, SessionOverlay::Connecting);

        let offline = state
            .core
            .devices
            .iter()
            .find(|device| !device.online)
            .expect("offline device")
            .id
            .clone();
        assert!(state.reduce_action(UserAction::Connect(offline)).is_empty());
    }

    #[test]
    fn discovery_and_default_quality_actions_update_the_expected_state() {
        let mut state = model();
        assert_eq!(
            state.reduce_action(UserAction::DiscoverDevices),
            vec![UiCommand::DiscoverDevices]
        );
        assert!(state
            .reduce_action(UserAction::SetDefaultQuality(QualityPreset::P1080))
            .is_empty());
        assert_eq!(state.default_quality, QualityPreset::P1080);

        let online = state
            .core
            .devices
            .iter()
            .find(|device| device.online && device.host_capable)
            .expect("online host")
            .id
            .clone();
        assert_eq!(
            state.reduce_action(UserAction::SelectDevice(online.clone())),
            vec![
                UiCommand::SelectDevice(online.clone()),
                UiCommand::SetQuality {
                    device_id: online,
                    quality: QualityPreset::P1080,
                },
            ]
        );
    }

    #[test]
    fn display_switch_holds_a_frame_until_decoder_ready() {
        let mut state = model();
        let device = state
            .core
            .devices
            .iter()
            .find(|device| device.online)
            .expect("online device")
            .clone();
        state.core.selected_device = Some(device.id.clone());
        let display = device.displays.first().expect("display").id;
        assert_eq!(
            state.reduce_action(UserAction::SelectDisplay(display)),
            vec![UiCommand::SelectDisplay {
                device_id: device.id.clone(),
                display_id: display
            }]
        );
        state.record_frame(8);
        assert_eq!(state.held_frame_id, Some(8));
        state.apply_event(CoreEvent::StreamStarted {
            device_id: device.id.clone(),
            display_id: display,
            width: 1280,
            height: 720,
            fps: 30,
        });
        assert_eq!(state.held_frame_id, Some(8));
        assert_eq!(state.overlay, SessionOverlay::Switching);
        state.apply_event(CoreEvent::DecoderReady {
            device_id: state.core.selected_device.clone().expect("selected"),
        });
        assert_eq!(state.held_frame_id, None);
        assert_eq!(state.overlay, SessionOverlay::None);
    }

    #[test]
    fn any_available_display_can_be_selected_and_unavailable_displays_are_ignored() {
        let mut state = model();
        let device_id = state.core.selected_device.clone().expect("selected device");
        let device = state
            .core
            .devices
            .iter()
            .find(|device| device.id == device_id)
            .expect("selected device snapshot");
        let selected = state.core.selected_display;
        let other_id = device
            .displays
            .iter()
            .find(|display| display.available && Some(display.id) != selected)
            .expect("another available display")
            .id;
        assert_eq!(
            state.reduce_action(UserAction::SelectDisplay(other_id)),
            vec![UiCommand::SelectDisplay {
                device_id: device_id.clone(),
                display_id: other_id,
            }]
        );

        let unavailable = state
            .core
            .devices
            .iter_mut()
            .find(|device| device.id == device_id)
            .and_then(|device| device.displays.iter_mut().next())
            .expect("display");
        unavailable.available = false;
        let unavailable_id = unavailable.id;
        assert!(state
            .reduce_action(UserAction::SelectDisplay(unavailable_id))
            .is_empty());
    }

    #[test]
    fn hide_pause_capture_and_quality_actions_emit_core_commands() {
        let mut state = model();
        assert_eq!(
            state.reduce_action(UserAction::SetVisible(false)),
            vec![UiCommand::SetVisible(false)]
        );
        assert_eq!(state.overlay, SessionOverlay::Paused);
        assert_eq!(
            state.reduce_action(UserAction::SetKeyboardCapture(true)),
            vec![UiCommand::ToggleKeyboardCapture(true)]
        );
        assert_eq!(
            state.reduce_action(UserAction::SetMouseCapture(true)),
            vec![UiCommand::ToggleMouseCapture(true)]
        );
        let selected = state
            .core
            .devices
            .iter()
            .find(|device| device.online)
            .expect("online")
            .id
            .clone();
        state.core.selected_device = Some(selected.clone());
        assert_eq!(
            state.reduce_action(UserAction::SetQuality(QualityPreset::P1080)),
            vec![UiCommand::SetQuality {
                device_id: selected,
                quality: QualityPreset::P1080
            }]
        );
        assert_eq!(state.session_quality, QualityPreset::P1080);
        assert_eq!(state.overlay, SessionOverlay::Switching);
        let mut updated = state.core.clone();
        updated.telemetry.host.width = 853;
        updated.telemetry.host.height = 480;
        updated.telemetry.session.last_rtt_us = Some(8_000);
        state.apply_snapshot(updated);
        assert_eq!(state.stream_dimensions, Some((853, 480)));
        state.reduce_action(UserAction::SetKeyboardCapture(false));
        state.reduce_action(UserAction::SetMouseCapture(false));
        assert_eq!(
            state.reduce_action(UserAction::ToggleRemoteDesktop),
            vec![
                UiCommand::ToggleKeyboardCapture(true),
                UiCommand::ToggleMouseCapture(true),
            ]
        );
        assert!(state.keyboard_capture && state.mouse_capture);
    }

    #[test]
    fn topology_removal_offline_and_authorization_events_update_view_state() {
        let mut state = model();
        let device = state.core.devices[0].id.clone();
        state.apply_event(CoreEvent::DeviceOffline {
            device_id: device.clone(),
        });
        assert!(
            !state
                .core
                .devices
                .iter()
                .find(|candidate| candidate.id == device)
                .expect("device")
                .online
        );
        state.apply_event(CoreEvent::PendingAuthorization {
            device_id: device.clone(),
            device_name: "New host".to_owned(),
        });
        assert!(matches!(
            &state.overlay,
            SessionOverlay::WaitingForApproval { .. }
        ));
        assert_eq!(
            state.reduce_action(UserAction::ApprovePeer(device.clone())),
            vec![UiCommand::ApprovePeer(device.clone())]
        );
        assert_eq!(
            state.reduce_action(UserAction::RemovePeer(device.clone())),
            vec![UiCommand::RemovePeer(device)]
        );
    }

    #[test]
    fn stale_stream_events_from_another_device_do_not_replace_the_selected_session() {
        let mut state = model();
        let selected = state.core.selected_device.clone().expect("selected device");
        let inactive = state
            .core
            .devices
            .iter()
            .find(|device| device.id != selected)
            .expect("inactive device")
            .id
            .clone();
        let display = state
            .core
            .devices
            .iter()
            .find(|device| device.id == inactive)
            .and_then(|device| device.displays.first())
            .expect("display")
            .id;
        let dimensions = state.stream_dimensions;
        let overlay = state.overlay.clone();
        state.apply_event(CoreEvent::StreamStarted {
            device_id: inactive.clone(),
            display_id: display,
            width: 854,
            height: 480,
            fps: 30,
        });
        state.apply_event(CoreEvent::StreamReset {
            device_id: inactive.clone(),
            epoch: 99,
            width: 640,
            height: 360,
        });
        state.apply_event(CoreEvent::DecoderReady {
            device_id: inactive.clone(),
        });
        state.apply_event(CoreEvent::SessionEnded {
            device_id: Some(inactive.clone()),
            reason: SessionEndReason::RemoteClosed,
        });
        state.apply_event(CoreEvent::VideoUnavailable {
            device_id: inactive,
        });
        assert_eq!(state.core.selected_device, Some(selected));
        assert_eq!(state.stream_dimensions, dimensions);
        assert_eq!(state.overlay, overlay);
    }

    #[test]
    fn removing_the_selected_display_clears_selection_and_shows_an_error_overlay() {
        let mut state = model();
        let device_id = state
            .core
            .selected_device
            .clone()
            .expect("fake selected device");
        let topology =
            racc_core::Topology::new(2, Vec::new(), None).expect("empty replacement topology");
        state.apply_event(CoreEvent::TopologyChanged {
            device_id,
            topology,
        });
        assert_eq!(state.core.selected_display, None);
        assert!(matches!(&state.overlay, SessionOverlay::Error(_)));
    }
}
