//! Pure app state transitions and user-action command generation.

use racc_core::ipc::{AllowlistEntry, HostStatus, IpcEvent, PendingPeer, MAX_PEER_LIST_ENTRIES};
use racc_core::{
    ClipboardStatus, CoreEvent, CoreSnapshot, DeviceId, DeviceSnapshot, QualityPreset,
    SessionEndReason, UiCommand,
};
use std::time::Instant;

/// Main shell view visible to the user.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub enum Page {
    /// Connected or selected remote desktop session.
    #[default]
    Session,
    /// Device discovery and hosting overview.
    Home,
    /// Local hosting and quality preferences.
    Settings,
    /// Product and third-party notices.
    About,
}

/// Current state of the Tailscale peer refresh shown on Home.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum DiscoveryState {
    /// No refresh has been requested in this app session.
    Idle,
    /// A refresh request has been issued and peer metadata is still arriving.
    Refreshing,
    /// A successful refresh completed with this many current peers.
    Updated { peer_count: usize },
    /// The last refresh attempt failed with a safe, user-facing message.
    Failed(String),
}

/// Session overlay state, rendered above the held or current frame.
#[derive(Clone, Debug, Default, Eq, Hash, PartialEq)]
pub enum SessionOverlay {
    /// No blocking session state.
    #[default]
    None,
    /// The selected device is being contacted.
    Connecting,
    /// A new display stream is being prepared while the prior frame remains visible.
    Switching,
    /// The viewer has paused the stream because the app is hidden.
    Paused,
    /// The viewer is reconnecting after the control connection was lost.
    Reconnecting,
    /// A peer is waiting for approval on the host.
    WaitingForApproval {
        device_id: DeviceId,
        device_name: String,
    },
    /// A stream or command error is being shown.
    Error(String),
}

/// Local action generated by a widget; it contains no widget or toolkit state.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum UserAction {
    /// Show the session page.
    Session,
    /// Show the home page.
    Home,
    /// Show settings.
    Settings,
    /// Show product and third-party notices.
    About,
    /// Rescan the fake core's known devices.
    DiscoverDevices,
    /// Change the quality used for future peer connections.
    SetDefaultQuality(QualityPreset),
    /// Select a device in the rail.
    SelectDevice(DeviceId),
    /// Connect to an available host from Home.
    Connect(DeviceId),
    /// Select a remote display.
    SelectDisplay(racc_core::DisplayId),
    /// Change viewer quality preference.
    SetQuality(QualityPreset),
    /// Show or hide the app window.
    SetVisible(bool),
    /// Enable or disable the combined keyboard and mouse remote desktop mode.
    ToggleRemoteDesktop,
    /// Toggle the keyboard capture mode.
    SetKeyboardCapture(bool),
    /// Toggle mouse capture mode.
    SetMouseCapture(bool),
    /// Toggle bidirectional text clipboard synchronization for the active session.
    ToggleClipboardSync,
    /// Disconnect the current session.
    Disconnect,
    /// Turn host mode on or off.
    SetHosting(bool),
    /// Start the app at sign-in or remove its current-user autostart entry.
    SetAutostart(bool),
    /// Approve an incoming peer.
    ApprovePeer(DeviceId),
    /// Reject an incoming peer.
    RejectPeer(DeviceId),
    /// Remove an approved peer from the allowlist.
    RemovePeer(DeviceId),
    /// Collapse or expand the device sidebar.
    ToggleDeviceSidebar,
    /// Collapse or expand the live telemetry sidebar.
    ToggleTelemetrySidebar,
}

/// State consumed by the widget tree. Widgets only render these values.
#[derive(Clone, Debug)]
pub struct ViewModel {
    /// Latest metadata snapshot from the core.
    pub core: CoreSnapshot,
    /// Current page.
    pub page: Page,
    /// Current Tailscale discovery state.
    pub discovery_state: DiscoveryState,
    /// Preferred quality applied when starting a peer session.
    pub default_quality: QualityPreset,
    /// Most recently selected quality preference for the active session.
    pub session_quality: QualityPreset,
    /// Current session overlay.
    pub overlay: SessionOverlay,
    /// Whether keyboard capture is enabled locally.
    pub keyboard_capture: bool,
    /// Whether the live keyboard reducer currently has focus and may forward input.
    pub keyboard_capture_active: bool,
    /// Whether mouse capture is enabled locally.
    pub mouse_capture: bool,
    /// Whether the live pointer reducer currently has focus and may forward input.
    pub mouse_capture_active: bool,
    /// Whether the device sidebar is collapsed.
    pub device_sidebar_collapsed: bool,
    /// Whether the telemetry sidebar is collapsed.
    pub telemetry_sidebar_collapsed: bool,
    /// Whether the app should start when the current user signs in.
    pub autostart_enabled: bool,
    /// Clipboard status label displayed in the sidebar.
    pub clipboard_status: String,
    /// Local monotonic time and direction of the latest completed clipboard transfer.
    pub clipboard_last_sync: Option<(Instant, racc_core::ClipboardTransferDirection)>,
    /// Most recent user-facing notification.
    pub notification: Option<String>,
    /// Last good frame identifier, retained across a stream reset.
    pub held_frame_id: Option<u32>,
    /// Active stream dimensions (stream content, not monitor dimensions).
    pub stream_dimensions: Option<(u32, u32)>,
    /// Whether this app instance has a live local host-agent worker.
    pub local_host_controls_available: bool,
    /// Whether the latest complete local IPC refresh succeeded.
    pub local_host_connected: bool,
    /// Actual status returned by the local host-agent.
    pub local_host_status: Option<HostStatus>,
    /// Approved local host-agent peers.
    pub local_host_allowlist: Vec<AllowlistEntry>,
    /// Local peers awaiting approval.
    pub local_host_pending: Vec<PendingPeer>,
    /// Safe, user-facing local host-agent error.
    pub local_host_error: Option<String>,
}

impl ViewModel {
    /// Creates initial app state from a core metadata snapshot.
    pub fn new(core: CoreSnapshot) -> Self {
        let width = u32::from(core.telemetry.host.width);
        let height = u32::from(core.telemetry.host.height);
        let stream_dimensions = (width > 0 && height > 0).then_some((width, height));
        Self {
            core,
            page: Page::Session,
            discovery_state: DiscoveryState::Idle,
            default_quality: QualityPreset::P720,
            session_quality: QualityPreset::P720,
            overlay: SessionOverlay::None,
            keyboard_capture: false,
            keyboard_capture_active: false,
            mouse_capture: false,
            mouse_capture_active: false,
            device_sidebar_collapsed: false,
            telemetry_sidebar_collapsed: false,
            autostart_enabled: false,
            clipboard_status: "Ready".to_owned(),
            clipboard_last_sync: None,
            notification: None,
            held_frame_id: None,
            stream_dimensions,
            local_host_controls_available: false,
            local_host_connected: false,
            local_host_status: None,
            local_host_allowlist: Vec::new(),
            local_host_pending: Vec::new(),
            local_host_error: None,
        }
    }

    /// Marks the initial launch refresh as active.
    pub fn begin_discovery(&mut self) {
        self.discovery_state = DiscoveryState::Refreshing;
    }

    /// Records a user-facing discovery startup or refresh error.
    pub fn set_discovery_error(&mut self, message: String) {
        self.discovery_state = DiscoveryState::Failed(message);
    }

    /// Replaces host status and peer data with the latest local IPC snapshot.
    pub fn apply_local_host_snapshot(&mut self, snapshot: crate::local_host::LocalHostSnapshot) {
        self.local_host_connected = snapshot.connected;
        self.local_host_status = snapshot.status;
        self.local_host_allowlist = snapshot.allowlist;
        if !snapshot.connected {
            self.local_host_pending.clear();
        }
        self.local_host_error = snapshot.error;
        self.core.hosting_enabled = self
            .local_host_status
            .as_ref()
            .is_some_and(|status| status.hosting_enabled);
    }

    /// Replaces pending host approvals from a subscription's initial snapshot.
    pub fn apply_local_host_pending_snapshot(&mut self, peers: Vec<PendingPeer>) {
        self.local_host_pending = peers.into_iter().take(MAX_PEER_LIST_ENTRIES).collect();
    }

    /// Applies one pending-approval event from the local host-agent subscription.
    pub fn apply_local_host_pending_event(&mut self, event: IpcEvent) {
        match event {
            IpcEvent::PendingAdded { peer } => {
                if let Some(existing) = self
                    .local_host_pending
                    .iter_mut()
                    .find(|existing| existing.node_id == peer.node_id)
                {
                    *existing = peer;
                } else if self.local_host_pending.len() < MAX_PEER_LIST_ENTRIES {
                    self.local_host_pending.push(peer);
                }
            }
            IpcEvent::PendingRemoved { node_id } => {
                self.local_host_pending
                    .retain(|peer| peer.node_id != node_id);
            }
        }
    }

    /// Applies one user action and returns core commands in order.
    pub fn reduce_action(&mut self, action: UserAction) -> Vec<UiCommand> {
        match action {
            UserAction::Session => self.page = Page::Session,
            UserAction::Home => self.page = Page::Home,
            UserAction::Settings => self.page = Page::Settings,
            UserAction::About => self.page = Page::About,
            UserAction::DiscoverDevices => {
                self.discovery_state = DiscoveryState::Refreshing;
                self.notification = None;
                return vec![UiCommand::DiscoverDevices];
            }
            UserAction::SetDefaultQuality(quality) => self.default_quality = quality,
            UserAction::SelectDevice(device_id) => {
                if self.device_online(&device_id) {
                    self.core.selected_device = Some(device_id.clone());
                    self.page = Page::Session;
                    self.overlay = SessionOverlay::Connecting;
                    self.session_quality = self.default_quality;
                    return vec![
                        UiCommand::SelectDevice(device_id.clone()),
                        UiCommand::SetQuality {
                            device_id,
                            quality: self.default_quality,
                        },
                    ];
                }
                return Vec::new();
            }
            UserAction::Connect(device_id) => {
                if self.device_online(&device_id) {
                    self.core.selected_device = Some(device_id.clone());
                    self.page = Page::Session;
                    self.overlay = SessionOverlay::Connecting;
                    self.session_quality = self.default_quality;
                    return vec![
                        UiCommand::Connect(device_id.clone()),
                        UiCommand::SetQuality {
                            device_id,
                            quality: self.default_quality,
                        },
                    ];
                }
                return Vec::new();
            }
            UserAction::SelectDisplay(display_id) => {
                let Some(device_id) = self.core.selected_device.clone() else {
                    return Vec::new();
                };
                if self.display_available(&device_id, display_id) {
                    self.core.selected_display = Some(display_id);
                    self.overlay = SessionOverlay::Switching;
                    return vec![UiCommand::SelectDisplay {
                        device_id,
                        display_id,
                    }];
                }
                return Vec::new();
            }
            UserAction::SetQuality(quality) => {
                let Some(device_id) = self.core.selected_device.clone() else {
                    return Vec::new();
                };
                self.session_quality = quality;
                if self.core.telemetry.session.last_rtt_us.is_some() {
                    self.overlay = SessionOverlay::Switching;
                }
                return vec![UiCommand::SetQuality { device_id, quality }];
            }
            UserAction::SetVisible(visible) => {
                self.core.visible = visible;
                if !visible {
                    self.overlay = SessionOverlay::Paused;
                } else if matches!(&self.overlay, SessionOverlay::Paused) {
                    self.overlay = SessionOverlay::None;
                }
                return vec![UiCommand::SetVisible(visible)];
            }
            UserAction::ToggleRemoteDesktop => {
                let enabled = !(self.keyboard_capture && self.mouse_capture);
                self.keyboard_capture = enabled;
                self.mouse_capture = enabled;
                return vec![
                    UiCommand::ToggleKeyboardCapture(enabled),
                    UiCommand::ToggleMouseCapture(enabled),
                ];
            }
            UserAction::SetKeyboardCapture(enabled) => {
                self.keyboard_capture = enabled;
                self.keyboard_capture_active = false;
                return vec![UiCommand::ToggleKeyboardCapture(enabled)];
            }
            UserAction::SetMouseCapture(enabled) => {
                self.mouse_capture = enabled;
                self.mouse_capture_active = false;
                return vec![UiCommand::ToggleMouseCapture(enabled)];
            }
            UserAction::ToggleClipboardSync => {
                if !self.core.clipboard_session_active {
                    return Vec::new();
                }
                let enabled = !self.core.clipboard_sync_enabled;
                self.core.clipboard_sync_enabled = enabled;
                return vec![UiCommand::SetClipboardEnabled(enabled)];
            }
            UserAction::Disconnect => {
                self.keyboard_capture = false;
                self.keyboard_capture_active = false;
                self.mouse_capture = false;
                self.mouse_capture_active = false;
                self.overlay = SessionOverlay::Reconnecting;
                return vec![UiCommand::Disconnect];
            }
            UserAction::SetHosting(enabled) => {
                self.core.hosting_enabled = enabled;
                return vec![UiCommand::SetHosting(enabled)];
            }
            UserAction::SetAutostart(enabled) => self.autostart_enabled = enabled,
            UserAction::ApprovePeer(device_id) => return vec![UiCommand::ApprovePeer(device_id)],
            UserAction::RejectPeer(device_id) => return vec![UiCommand::RejectPeer(device_id)],
            UserAction::RemovePeer(device_id) => return vec![UiCommand::RemovePeer(device_id)],
            UserAction::ToggleDeviceSidebar => {
                self.device_sidebar_collapsed = !self.device_sidebar_collapsed;
            }
            UserAction::ToggleTelemetrySidebar => {
                self.telemetry_sidebar_collapsed = !self.telemetry_sidebar_collapsed;
            }
        }
        Vec::new()
    }

    /// Replaces metadata from a fresh core snapshot and refreshes stream dimensions.
    pub fn apply_snapshot(&mut self, snapshot: CoreSnapshot) {
        let width = u32::from(snapshot.telemetry.host.width);
        let height = u32::from(snapshot.telemetry.host.height);
        if snapshot.telemetry.session.last_rtt_us.is_some() && width > 0 && height > 0 {
            self.stream_dimensions = Some((width, height));
        }
        self.core = snapshot;
    }

    /// Applies one metadata event from the core. Video pixels are never consumed here.
    pub fn apply_event(&mut self, event: CoreEvent) {
        match event {
            CoreEvent::DeviceDiscovered(device) => upsert_device(&mut self.core.devices, device),
            CoreEvent::DeviceOffline { device_id } => {
                if let Some(device) = self
                    .core
                    .devices
                    .iter_mut()
                    .find(|device| device.id == device_id)
                {
                    device.online = false;
                }
            }
            CoreEvent::TopologyChanged {
                device_id,
                topology,
            } => {
                let selected_device = self.core.selected_device.as_ref() == Some(&device_id);
                if let Some(device) = self
                    .core
                    .devices
                    .iter_mut()
                    .find(|device| device.id == device_id)
                {
                    device.displays = topology
                        .displays()
                        .iter()
                        .map(racc_core::DisplaySnapshot::from)
                        .collect();
                }
                if selected_device {
                    let previously_selected = self.core.selected_display;
                    let current_available = self.core.selected_display.is_some_and(|selected| {
                        self.core
                            .devices
                            .iter()
                            .find(|device| device.id == device_id)
                            .is_some_and(|device| {
                                device
                                    .displays
                                    .iter()
                                    .any(|display| display.id == selected && display.available)
                            })
                    });
                    if !current_available {
                        self.core.selected_display = self
                            .core
                            .devices
                            .iter()
                            .find(|device| device.id == device_id)
                            .and_then(|device| {
                                device
                                    .displays
                                    .iter()
                                    .find(|display| display.available && display.primary)
                                    .or_else(|| {
                                        device.displays.iter().find(|display| display.available)
                                    })
                            })
                            .map(|display| display.id);
                        if previously_selected.is_some() {
                            self.overlay = SessionOverlay::Error(
                                "The selected display is no longer available".to_owned(),
                            );
                            self.held_frame_id = None;
                        }
                    }
                }
            }
            CoreEvent::DisplaySelected {
                device_id,
                display_id,
            } => {
                if self.core.selected_device.as_ref() == Some(&device_id) {
                    self.core.selected_display = Some(display_id);
                    self.overlay = SessionOverlay::Switching;
                }
            }
            CoreEvent::StreamStarted {
                device_id,
                display_id,
                width,
                height,
                ..
            } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.core.selected_display = Some(display_id);
                self.stream_dimensions = Some((u32::from(width), u32::from(height)));
            }
            CoreEvent::StreamReset {
                device_id,
                width,
                height,
                ..
            } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.stream_dimensions = Some((u32::from(width), u32::from(height)));
                self.overlay = SessionOverlay::Switching;
            }
            CoreEvent::DecoderReady { device_id } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.overlay = SessionOverlay::None;
                self.held_frame_id = None;
            }
            CoreEvent::DeviceDiscoveryCompleted {
                peer_count,
                local_device_name,
            } => {
                if let Some(local_device_name) = local_device_name {
                    if !local_device_name.trim().is_empty() {
                        self.core.local_device_name = local_device_name;
                    }
                }
                self.discovery_state = DiscoveryState::Updated { peer_count };
            }
            CoreEvent::ConnectionStatsUpdated(telemetry) => self.core.telemetry = telemetry,
            CoreEvent::InputCaptureChanged { keyboard, mouse } => {
                self.keyboard_capture = keyboard;
                self.mouse_capture = mouse;
            }
            CoreEvent::SessionEnded { device_id, reason } => {
                if device_id
                    .as_ref()
                    .is_some_and(|id| self.core.selected_device.as_ref() != Some(id))
                {
                    return;
                }
                self.overlay = match reason {
                    SessionEndReason::StreamFailure => {
                        SessionOverlay::Error("The remote stream ended unexpectedly".to_owned())
                    }
                    SessionEndReason::Disconnected => SessionOverlay::None,
                    SessionEndReason::RemoteClosed | SessionEndReason::ControlTimeout => {
                        SessionOverlay::Reconnecting
                    }
                };
                self.keyboard_capture = false;
                self.keyboard_capture_active = false;
                self.mouse_capture = false;
                self.mouse_capture_active = false;
            }
            CoreEvent::PendingAuthorization {
                device_id,
                device_name,
            } => {
                self.overlay = SessionOverlay::WaitingForApproval {
                    device_id,
                    device_name,
                };
            }
            CoreEvent::ClipboardStatus(status) => self.clipboard_status = clipboard_label(status),
            CoreEvent::Notification(notification) => {
                if notification.title == "Device discovery failed" {
                    self.discovery_state = DiscoveryState::Failed(notification.message.clone());
                }
                self.notification =
                    Some(format!("{}: {}", notification.title, notification.message))
            }
            CoreEvent::VideoUnavailable { device_id } => {
                if self.core.selected_device.as_ref() != Some(&device_id) {
                    return;
                }
                self.overlay = SessionOverlay::Error("Video is unavailable".to_owned())
            }
        }
    }

    /// Applies the latest live telemetry snapshot from the bounded runtime slot.
    pub fn apply_live_telemetry(&mut self, telemetry: racc_telemetry::TelemetrySnapshot) {
        let width = u32::from(telemetry.host.width);
        let height = u32::from(telemetry.host.height);
        if telemetry.session.epoch > 0 && width > 0 && height > 0 {
            self.stream_dimensions = Some((width, height));
        }
        self.core.telemetry = telemetry;
    }

    /// Applies content-free clipboard transfer status from the separate runtime port.
    pub fn apply_clipboard_metadata(&mut self, metadata: racc_core::ClipboardMetadata) {
        use racc_core::{
            ClipboardTransferDirection as Direction, ClipboardTransferStatus as Status,
        };
        let sequence = metadata
            .sequence
            .map_or_else(String::new, |sequence| format!(" #{sequence}"));
        if matches!(metadata.status, Status::Sent | Status::AdapterApplied) {
            self.clipboard_last_sync = Some((Instant::now(), metadata.direction));
        }
        self.clipboard_status = match (metadata.direction, metadata.status) {
            (_, Status::Enabled) => "Text clipboard sync enabled".to_owned(),
            (_, Status::Disabled) => "Sync disabled".to_owned(),
            (_, Status::Sent) => format!("Sent text update{sequence}"),
            (_, Status::ReceivedPendingApply) => {
                format!("Received text update{sequence} · clipboard apply pending")
            }
            (_, Status::AdapterApplied) => {
                format!("Applied received text update{sequence}")
            }
            (Direction::LocalToRemote, Status::AdapterFailed) => {
                self.core.clipboard_sync_enabled = false;
                self.notification = Some(
                    "The local clipboard adapter failed; clipboard sync was disabled.".to_owned(),
                );
                "Clipboard sync disabled · local adapter error".to_owned()
            }
            (Direction::RemoteToLocal, Status::AdapterFailed) => {
                self.notification = Some("Could not apply remote clipboard text.".to_owned());
                "Remote clipboard apply failed".to_owned()
            }
            (_, Status::ApplyQueueFull) => {
                "Latest remote text queued · an older pending apply was replaced".to_owned()
            }
            (_, Status::RejectedTooLarge) => {
                self.notification = Some("Clipboard text exceeded the 512 KiB limit.".to_owned());
                "Clipboard text rejected · over size limit".to_owned()
            }
            (_, Status::RejectedInvalidUtf8) => {
                self.notification = Some("Clipboard update was not valid UTF-8.".to_owned());
                "Clipboard update rejected · invalid text".to_owned()
            }
            (_, Status::Ignored) => "Duplicate or echo ignored".to_owned(),
            (Direction::LocalToRemote, Status::Queued) => "Local text update queued".to_owned(),
            (Direction::RemoteToLocal, Status::Queued) => "Remote text update queued".to_owned(),
        };
    }

    /// Summarizes the last completed transfer using viewer-local monotonic time.
    pub fn clipboard_last_sync_label(&self) -> String {
        let Some((synced_at, direction)) = self.clipboard_last_sync else {
            return "No clipboard sync yet".to_owned();
        };
        let elapsed = synced_at.elapsed().as_secs();
        let age = if elapsed < 5 {
            "just now".to_owned()
        } else if elapsed < 60 {
            format!("{elapsed}s ago")
        } else if elapsed < 3_600 {
            format!("{}m ago", elapsed / 60)
        } else {
            format!("{}h ago", elapsed / 3_600)
        };
        let direction = match direction {
            racc_core::ClipboardTransferDirection::LocalToRemote => "this device to peer",
            racc_core::ClipboardTransferDirection::RemoteToLocal => "peer to this device",
        };
        format!("{age} · {direction}")
    }

    /// Applies one live viewer runtime event to UI metadata state.
    ///
    /// Decoded frames stay on FrameSource; this mapper receives only bounded
    /// lifecycle, topology, and statistics metadata.
    pub fn apply_viewer_event(
        &mut self,
        device_id: &DeviceId,
        event: racc_core::ViewerRuntimeEvent,
    ) {
        use racc_telemetry::{CodecKind, ConnectionState, HostSnapshot};
        match event {
            racc_core::ViewerRuntimeEvent::Connecting => {
                self.overlay = SessionOverlay::Connecting;
                self.core.telemetry.session.connection_state = ConnectionState::Connecting;
                self.core.telemetry.session.decoder = racc_telemetry::DecoderKind::Unknown;
            }
            racc_core::ViewerRuntimeEvent::Connected(ack) => {
                let displays = self
                    .core
                    .devices
                    .iter()
                    .find(|device| &device.id == device_id)
                    .map(|device| device.displays.clone())
                    .unwrap_or_default();
                upsert_device(
                    &mut self.core.devices,
                    DeviceSnapshot {
                        id: device_id.clone(),
                        name: ack.device_name,
                        os: ack.os,
                        online: true,
                        host_capable: true,
                        displays,
                        streamed_display: self.core.selected_display,
                    },
                );
                self.core.selected_device = Some(device_id.clone());
                self.core.telemetry.session.connection_state = ConnectionState::Connected;
                self.core.telemetry.session.codec = CodecKind::H264;
                self.core.clipboard_session_active = true;
                self.overlay = SessionOverlay::Connecting;
            }
            racc_core::ViewerRuntimeEvent::TopologyChanged(topology) => {
                let streamed = topology
                    .streamed_display_id()
                    .or_else(|| topology.primary_display_id());
                self.apply_event(CoreEvent::TopologyChanged {
                    device_id: device_id.clone(),
                    topology,
                });
                if self.core.selected_device.as_ref() == Some(device_id) {
                    if let Some(display_id) = streamed {
                        self.core.selected_display = Some(display_id);
                    }
                }
            }
            racc_core::ViewerRuntimeEvent::StreamReset(reset) => {
                if reset.status != racc_proto::StreamStatus::Ok {
                    self.overlay = SessionOverlay::Error(format!(
                        "Host could not start the stream: {:?}",
                        reset.status
                    ));
                    return;
                }
                if self.core.selected_device.as_ref() != Some(device_id) {
                    return;
                }
                if let Some(display_id) = racc_core::DisplayId::new(reset.display_id) {
                    self.core.selected_display = Some(display_id);
                }
                self.core.telemetry.session.epoch = reset.epoch;
                self.core.telemetry.session.codec = CodecKind::H264;
                self.core.telemetry.host.width = reset.width;
                self.core.telemetry.host.height = reset.height;
                self.apply_event(CoreEvent::StreamReset {
                    device_id: device_id.clone(),
                    epoch: reset.epoch,
                    width: reset.width,
                    height: reset.height,
                });
            }
            racc_core::ViewerRuntimeEvent::FrameAvailable { epoch, .. } => {
                if self.core.selected_device.as_ref() == Some(device_id)
                    && self.core.telemetry.session.epoch == epoch
                {
                    self.apply_event(CoreEvent::DecoderReady {
                        device_id: device_id.clone(),
                    });
                }
            }
            racc_core::ViewerRuntimeEvent::DecoderSelected(decoder) => {
                self.core.telemetry.session.decoder = decoder;
            }
            racc_core::ViewerRuntimeEvent::HostStats(report) => {
                self.core.telemetry.host = HostSnapshot::from_stats_report(report);
            }
            racc_core::ViewerRuntimeEvent::Session(event) => match event {
                racc_session::SessionEvent::Connected | racc_session::SessionEvent::Reconnected => {
                    self.core.telemetry.session.connection_state = ConnectionState::Connected;
                }
                racc_session::SessionEvent::Reconnecting => {
                    self.core.telemetry.session.connection_state = ConnectionState::Reconnecting;
                    self.core.clipboard_session_active = false;
                    self.core.clipboard_sync_enabled = false;
                    self.overlay = SessionOverlay::Reconnecting;
                }
                racc_session::SessionEvent::DisplaySelected(display_id) => {
                    if self.core.selected_device.as_ref() == Some(device_id) {
                        self.core.selected_display = Some(display_id);
                    }
                }
                racc_session::SessionEvent::DisplayUnavailable(display_id) => {
                    self.overlay = SessionOverlay::Error(format!(
                        "Display {} is unavailable",
                        display_id.get()
                    ));
                }
                racc_session::SessionEvent::SessionEnded
                | racc_session::SessionEvent::ControlTimedOut => {
                    self.core.telemetry.session.connection_state = ConnectionState::Disconnected;
                    self.core.clipboard_session_active = false;
                    self.core.clipboard_sync_enabled = false;
                    self.overlay = SessionOverlay::Error(
                        "The remote session ended; reconnect manually with --connect".to_owned(),
                    );
                }
                other => self.notification = Some(format!("Remote session: {other:?}")),
            },
            racc_core::ViewerRuntimeEvent::Disconnected => {
                self.core.telemetry.session.connection_state = ConnectionState::Disconnected;
                self.core.clipboard_session_active = false;
                self.core.clipboard_sync_enabled = false;
                self.overlay = SessionOverlay::Error(
                    "Connection closed; reconnect manually with --connect".to_owned(),
                );
                self.keyboard_capture = false;
                self.keyboard_capture_active = false;
                self.mouse_capture = false;
                self.mouse_capture_active = false;
            }
            racc_core::ViewerRuntimeEvent::Failed(message) => {
                self.core.telemetry.session.connection_state = ConnectionState::Disconnected;
                self.core.clipboard_session_active = false;
                self.core.clipboard_sync_enabled = false;
                self.overlay = SessionOverlay::Error(message.clone());
                self.notification = Some(message);
                self.keyboard_capture = false;
                self.keyboard_capture_active = false;
                self.mouse_capture = false;
                self.mouse_capture_active = false;
            }
            racc_core::ViewerRuntimeEvent::VisibilityChanged(visible) => {
                self.core.visible = visible;
                if !visible {
                    self.overlay = SessionOverlay::Paused;
                }
            }
            racc_core::ViewerRuntimeEvent::CursorPosition(_)
            | racc_core::ViewerRuntimeEvent::CursorShape(_) => {}
        }
    }

    /// Records the most recent frame metadata without placing frame data on the event bus.
    pub fn record_frame(&mut self, frame_id: u32) {
        if matches!(&self.overlay, SessionOverlay::Switching) {
            self.held_frame_id = self.held_frame_id.or(Some(frame_id));
        }
    }

    fn device_online(&self, id: &DeviceId) -> bool {
        self.core
            .devices
            .iter()
            .any(|device| &device.id == id && device.online && device.host_capable)
    }

    fn display_available(&self, device_id: &DeviceId, display_id: racc_core::DisplayId) -> bool {
        self.core.devices.iter().any(|device| {
            &device.id == device_id
                && device
                    .displays
                    .iter()
                    .any(|display| display.id == display_id && display.available)
        })
    }
}

fn upsert_device(devices: &mut Vec<DeviceSnapshot>, device: DeviceSnapshot) {
    if let Some(existing) = devices.iter_mut().find(|existing| existing.id == device.id) {
        *existing = device;
    } else {
        devices.push(device);
    }
}

fn clipboard_label(status: ClipboardStatus) -> String {
    match status {
        ClipboardStatus::Ready => "Ready".to_owned(),
        ClipboardStatus::Received { sequence } => format!("Received text update #{sequence}"),
        ClipboardStatus::Sent { sequence } => format!("Sent text update #{sequence}"),
        ClipboardStatus::Failed { message } => format!("Clipboard error: {message}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use racc_core::CoreHandle;
    use racc_testkit::FakeCore;
    use racc_topology::{Display, DisplayFlags};

    fn model() -> ViewModel {
        let fake = FakeCore::new(41);
        ViewModel::new(fake.snapshot().expect("fake snapshot"))
    }

    #[test]
    fn local_host_status_replaces_saved_hosting_state() {
        let mut state = model();
        state.local_host_controls_available = true;
        state.core.hosting_enabled = true;

        state.apply_local_host_snapshot(crate::local_host::LocalHostSnapshot::default());
        assert!(!state.core.hosting_enabled);
        assert!(!state.local_host_connected);
        assert!(state.local_host_status.is_none());

        state.apply_local_host_snapshot(crate::local_host::LocalHostSnapshot {
            connected: true,
            status: Some(HostStatus {
                hosting_enabled: false,
                helper_state: racc_core::ipc::HelperState::Running,
                connected_viewers: 1,
                pending_approvals: 0,
            }),
            allowlist: Vec::new(),
            error: None,
        });
        assert!(state.local_host_connected);
        assert!(!state.core.hosting_enabled);
        assert_eq!(
            state
                .local_host_status
                .as_ref()
                .map(|status| status.connected_viewers),
            Some(1)
        );
    }

    #[test]
    fn local_host_pending_subscription_applies_snapshots_and_events() {
        let mut state = model();
        state.apply_local_host_pending_snapshot(vec![PendingPeer {
            node_id: "peer-a".to_owned(),
            display_name: "A".to_owned(),
            login_name: String::new(),
        }]);
        state.apply_local_host_pending_event(IpcEvent::PendingAdded {
            peer: PendingPeer {
                node_id: "peer-b".to_owned(),
                display_name: "B".to_owned(),
                login_name: "owner@example.invalid".to_owned(),
            },
        });
        state.apply_local_host_pending_event(IpcEvent::PendingAdded {
            peer: PendingPeer {
                node_id: "peer-a".to_owned(),
                display_name: "A renamed".to_owned(),
                login_name: String::new(),
            },
        });
        assert_eq!(state.local_host_pending.len(), 2);
        assert_eq!(state.local_host_pending[0].display_name, "A renamed");

        state.apply_local_host_pending_event(IpcEvent::PendingRemoved {
            node_id: "peer-b".to_owned(),
        });
        assert_eq!(state.local_host_pending.len(), 1);
        assert_eq!(state.local_host_pending[0].node_id, "peer-a");
    }

    #[test]
    fn autostart_action_updates_the_persistable_preference_without_core_commands() {
        let mut state = model();
        assert!(!state.autostart_enabled);
        assert!(state
            .reduce_action(UserAction::SetAutostart(true))
            .is_empty());
        assert!(state.autostart_enabled);
        assert!(state
            .reduce_action(UserAction::SetAutostart(false))
            .is_empty());
        assert!(!state.autostart_enabled);
    }

    #[test]
    fn about_action_opens_the_notices_page_without_core_commands() {
        let mut state = model();
        assert!(state.reduce_action(UserAction::About).is_empty());
        assert_eq!(state.page, Page::About);
    }

    #[test]
    fn selecting_online_device_emits_selection_but_offline_is_ignored() {
        let mut state = model();
        let online = state
            .core
            .devices
            .iter()
            .find(|device| device.online)
            .expect("online device")
            .id
            .clone();
        let offline = state
            .core
            .devices
            .iter()
            .find(|device| !device.online)
            .expect("offline device")
            .id
            .clone();
        assert_eq!(
            state.reduce_action(UserAction::SelectDevice(online.clone())),
            vec![
                UiCommand::SelectDevice(online.clone()),
                UiCommand::SetQuality {
                    device_id: online,
                    quality: QualityPreset::P720,
                },
            ]
        );
        assert!(matches!(&state.overlay, SessionOverlay::Connecting));
        assert!(state
            .reduce_action(UserAction::SelectDevice(offline))
            .is_empty());
    }

    #[test]
    fn home_connect_uses_the_connect_command_for_available_hosts() {
        let mut state = model();
        let online = state
            .core
            .devices
            .iter()
            .find(|device| device.online && device.host_capable)
            .expect("online host")
            .id
            .clone();
        assert_eq!(
            state.reduce_action(UserAction::Connect(online.clone())),
            vec![
                UiCommand::Connect(online.clone()),
                UiCommand::SetQuality {
                    device_id: online.clone(),
                    quality: QualityPreset::P720,
                },
            ]
        );
        assert_eq!(state.core.selected_device, Some(online));
        assert_eq!(state.page, Page::Session);
        assert_eq!(state.overlay, SessionOverlay::Connecting);

        let offline = state
            .core
            .devices
            .iter()
            .find(|device| !device.online)
            .expect("offline device")
            .id
            .clone();
        assert!(state.reduce_action(UserAction::Connect(offline)).is_empty());
    }

    #[test]
    fn discovery_action_reports_refreshing_then_updated_for_online_and_offline_peers() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        state.begin_discovery();
        assert_eq!(state.discovery_state, DiscoveryState::Refreshing);
        assert_eq!(
            state.reduce_action(UserAction::DiscoverDevices),
            vec![UiCommand::DiscoverDevices]
        );
        assert_eq!(state.discovery_state, DiscoveryState::Refreshing);

        let online_id = DeviceId::new("tailnet-node-online").expect("online device id");
        state.apply_event(CoreEvent::DeviceDiscovered(DeviceSnapshot {
            id: online_id.clone(),
            name: "Windows host".to_owned(),
            os: racc_proto::OsType::Windows,
            online: true,
            host_capable: true,
            displays: Vec::new(),
            streamed_display: None,
        }));
        assert_eq!(state.discovery_state, DiscoveryState::Refreshing);
        state.apply_event(CoreEvent::DeviceDiscoveryCompleted {
            peer_count: 1,
            local_device_name: Some("local machine".to_owned()),
        });
        assert_eq!(
            state.discovery_state,
            DiscoveryState::Updated { peer_count: 1 }
        );
        assert_eq!(state.core.local_device_name, "local machine");
        assert_eq!(state.core.devices.len(), 1);
        assert_eq!(
            state.reduce_action(UserAction::Connect(online_id.clone())),
            vec![
                UiCommand::Connect(online_id.clone()),
                UiCommand::SetQuality {
                    device_id: online_id,
                    quality: QualityPreset::P720,
                },
            ]
        );

        let offline_id = DeviceId::new("tailnet-node-offline").expect("offline device id");
        state.apply_event(CoreEvent::DeviceDiscovered(DeviceSnapshot {
            id: offline_id.clone(),
            name: "Offline Mac".to_owned(),
            os: racc_proto::OsType::MacOs,
            online: false,
            host_capable: false,
            displays: Vec::new(),
            streamed_display: None,
        }));
        assert_eq!(state.core.devices.len(), 2);
        assert!(state
            .core
            .devices
            .iter()
            .any(|device| device.id == offline_id && !device.online && !device.host_capable));
        assert!(state
            .reduce_action(UserAction::Connect(
                DeviceId::new("tailnet-node-offline").unwrap()
            ))
            .is_empty());
        state.reduce_action(UserAction::DiscoverDevices);
        state.apply_event(CoreEvent::DeviceDiscoveryCompleted {
            peer_count: 0,
            local_device_name: None,
        });
        assert_eq!(
            state.discovery_state,
            DiscoveryState::Updated { peer_count: 0 }
        );
    }

    #[test]
    fn discovery_failure_is_visible_and_a_new_refresh_clears_the_error() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        state.apply_event(CoreEvent::Notification(racc_core::Notification {
            level: racc_core::NotificationLevel::Warning,
            title: "Device discovery failed".to_owned(),
            message: "Tailscale is unavailable".to_owned(),
        }));
        assert_eq!(
            state.discovery_state,
            DiscoveryState::Failed("Tailscale is unavailable".to_owned())
        );
        state.reduce_action(UserAction::DiscoverDevices);
        assert_eq!(state.discovery_state, DiscoveryState::Refreshing);
        assert!(state.notification.is_none());
    }

    #[test]
    fn discovery_and_default_quality_actions_update_the_expected_state() {
        let mut state = model();
        assert_eq!(
            state.reduce_action(UserAction::DiscoverDevices),
            vec![UiCommand::DiscoverDevices]
        );
        assert!(state
            .reduce_action(UserAction::SetDefaultQuality(QualityPreset::P1080))
            .is_empty());
        assert_eq!(state.default_quality, QualityPreset::P1080);

        let online = state
            .core
            .devices
            .iter()
            .find(|device| device.online && device.host_capable)
            .expect("online host")
            .id
            .clone();
        assert_eq!(
            state.reduce_action(UserAction::SelectDevice(online.clone())),
            vec![
                UiCommand::SelectDevice(online.clone()),
                UiCommand::SetQuality {
                    device_id: online,
                    quality: QualityPreset::P1080,
                },
            ]
        );
    }

    #[test]
    fn display_switch_holds_a_frame_until_decoder_ready() {
        let mut state = model();
        let device = state
            .core
            .devices
            .iter()
            .find(|device| device.online)
            .expect("online device")
            .clone();
        state.core.selected_device = Some(device.id.clone());
        let display = device.displays.first().expect("display").id;
        assert_eq!(
            state.reduce_action(UserAction::SelectDisplay(display)),
            vec![UiCommand::SelectDisplay {
                device_id: device.id.clone(),
                display_id: display
            }]
        );
        state.record_frame(8);
        assert_eq!(state.held_frame_id, Some(8));
        state.apply_event(CoreEvent::StreamStarted {
            device_id: device.id.clone(),
            display_id: display,
            width: 1280,
            height: 720,
            fps: 30,
        });
        assert_eq!(state.held_frame_id, Some(8));
        assert_eq!(state.overlay, SessionOverlay::Switching);
        state.apply_event(CoreEvent::DecoderReady {
            device_id: state.core.selected_device.clone().expect("selected"),
        });
        assert_eq!(state.held_frame_id, None);
        assert_eq!(state.overlay, SessionOverlay::None);
    }

    #[test]
    fn any_available_display_can_be_selected_and_unavailable_displays_are_ignored() {
        let mut state = model();
        let device_id = state.core.selected_device.clone().expect("selected device");
        let device = state
            .core
            .devices
            .iter()
            .find(|device| device.id == device_id)
            .expect("selected device snapshot");
        let selected = state.core.selected_display;
        let other_id = device
            .displays
            .iter()
            .find(|display| display.available && Some(display.id) != selected)
            .expect("another available display")
            .id;
        assert_eq!(
            state.reduce_action(UserAction::SelectDisplay(other_id)),
            vec![UiCommand::SelectDisplay {
                device_id: device_id.clone(),
                display_id: other_id,
            }]
        );

        let unavailable = state
            .core
            .devices
            .iter_mut()
            .find(|device| device.id == device_id)
            .and_then(|device| device.displays.iter_mut().next())
            .expect("display");
        unavailable.available = false;
        let unavailable_id = unavailable.id;
        assert!(state
            .reduce_action(UserAction::SelectDisplay(unavailable_id))
            .is_empty());
    }

    #[test]
    fn hide_pause_capture_and_quality_actions_emit_core_commands() {
        let mut state = model();
        assert_eq!(
            state.reduce_action(UserAction::SetVisible(false)),
            vec![UiCommand::SetVisible(false)]
        );
        assert_eq!(state.overlay, SessionOverlay::Paused);
        assert_eq!(
            state.reduce_action(UserAction::SetKeyboardCapture(true)),
            vec![UiCommand::ToggleKeyboardCapture(true)]
        );
        assert_eq!(
            state.reduce_action(UserAction::SetMouseCapture(true)),
            vec![UiCommand::ToggleMouseCapture(true)]
        );
        let selected = state
            .core
            .devices
            .iter()
            .find(|device| device.online)
            .expect("online")
            .id
            .clone();
        state.core.selected_device = Some(selected.clone());
        assert_eq!(
            state.reduce_action(UserAction::SetQuality(QualityPreset::P1080)),
            vec![UiCommand::SetQuality {
                device_id: selected,
                quality: QualityPreset::P1080
            }]
        );
        assert_eq!(state.session_quality, QualityPreset::P1080);
        assert_eq!(state.overlay, SessionOverlay::Switching);
        let mut updated = state.core.clone();
        updated.telemetry.host.width = 853;
        updated.telemetry.host.height = 480;
        updated.telemetry.session.last_rtt_us = Some(8_000);
        state.apply_snapshot(updated);
        assert_eq!(state.stream_dimensions, Some((853, 480)));
        state.reduce_action(UserAction::SetKeyboardCapture(false));
        state.reduce_action(UserAction::SetMouseCapture(false));
        assert_eq!(
            state.reduce_action(UserAction::ToggleRemoteDesktop),
            vec![
                UiCommand::ToggleKeyboardCapture(true),
                UiCommand::ToggleMouseCapture(true),
            ]
        );
        assert!(state.keyboard_capture && state.mouse_capture);
    }

    #[test]
    fn topology_removal_offline_and_authorization_events_update_view_state() {
        let mut state = model();
        let device = state.core.devices[0].id.clone();
        state.apply_event(CoreEvent::DeviceOffline {
            device_id: device.clone(),
        });
        assert!(
            !state
                .core
                .devices
                .iter()
                .find(|candidate| candidate.id == device)
                .expect("device")
                .online
        );
        state.apply_event(CoreEvent::PendingAuthorization {
            device_id: device.clone(),
            device_name: "New host".to_owned(),
        });
        assert!(matches!(
            &state.overlay,
            SessionOverlay::WaitingForApproval { .. }
        ));
        assert_eq!(
            state.reduce_action(UserAction::ApprovePeer(device.clone())),
            vec![UiCommand::ApprovePeer(device.clone())]
        );
        assert_eq!(
            state.reduce_action(UserAction::RemovePeer(device.clone())),
            vec![UiCommand::RemovePeer(device)]
        );
    }

    #[test]
    fn live_telemetry_and_clipboard_metadata_update_only_bounded_ui_state() {
        let mut state = model();
        let mut hub = racc_telemetry::TelemetryHub::new();
        hub.record_rtt(1, 25_001);
        hub.record_loss(1, 0.02, 0.01);
        let telemetry = hub.snapshot(1);
        state.apply_live_telemetry(telemetry);
        assert_eq!(state.core.telemetry.session.last_rtt_us, Some(25_001));
        assert_eq!(state.core.telemetry.session.loss_fraction, 0.02);

        state.apply_clipboard_metadata(racc_core::ClipboardMetadata {
            direction: racc_core::ClipboardTransferDirection::RemoteToLocal,
            sequence: Some(9),
            byte_len: Some(7),
            status: racc_core::ClipboardTransferStatus::ReceivedPendingApply,
        });
        assert_eq!(
            state.clipboard_status,
            "Received text update #9 · clipboard apply pending"
        );
        assert!(!state.clipboard_status.contains("secret"));

        state.apply_clipboard_metadata(racc_core::ClipboardMetadata {
            direction: racc_core::ClipboardTransferDirection::RemoteToLocal,
            sequence: None,
            byte_len: Some(524_289),
            status: racc_core::ClipboardTransferStatus::RejectedTooLarge,
        });
        assert_eq!(
            state.notification.as_deref(),
            Some("Clipboard text exceeded the 512 KiB limit.")
        );
    }

    #[test]
    fn clipboard_last_sync_tracks_only_completed_transfers_and_direction() {
        let mut state = model();
        assert_eq!(state.clipboard_last_sync_label(), "No clipboard sync yet");

        state.apply_clipboard_metadata(racc_core::ClipboardMetadata {
            direction: racc_core::ClipboardTransferDirection::RemoteToLocal,
            sequence: Some(7),
            byte_len: Some(12),
            status: racc_core::ClipboardTransferStatus::ReceivedPendingApply,
        });
        assert!(state.clipboard_last_sync.is_none());

        state.apply_clipboard_metadata(racc_core::ClipboardMetadata {
            direction: racc_core::ClipboardTransferDirection::LocalToRemote,
            sequence: Some(8),
            byte_len: Some(4),
            status: racc_core::ClipboardTransferStatus::Sent,
        });
        assert_eq!(
            state.clipboard_last_sync.map(|(_, direction)| direction),
            Some(racc_core::ClipboardTransferDirection::LocalToRemote)
        );
        assert!(state
            .clipboard_last_sync_label()
            .contains("this device to peer"));

        state.apply_clipboard_metadata(racc_core::ClipboardMetadata {
            direction: racc_core::ClipboardTransferDirection::RemoteToLocal,
            sequence: Some(9),
            byte_len: Some(5),
            status: racc_core::ClipboardTransferStatus::AdapterApplied,
        });
        assert_eq!(
            state.clipboard_last_sync.map(|(_, direction)| direction),
            Some(racc_core::ClipboardTransferDirection::RemoteToLocal)
        );
        assert!(state
            .clipboard_last_sync_label()
            .contains("peer to this device"));
    }

    #[test]
    fn clipboard_adapter_error_metadata_is_content_free_and_disables_sync() {
        let mut state = model();
        state.core.clipboard_sync_enabled = true;
        state.apply_clipboard_metadata(racc_core::ClipboardMetadata {
            direction: racc_core::ClipboardTransferDirection::LocalToRemote,
            sequence: None,
            byte_len: None,
            status: racc_core::ClipboardTransferStatus::AdapterFailed,
        });
        assert!(!state.core.clipboard_sync_enabled);
        assert_eq!(
            state.clipboard_status,
            "Clipboard sync disabled · local adapter error"
        );
        assert_eq!(
            state.notification.as_deref(),
            Some("The local clipboard adapter failed; clipboard sync was disabled.")
        );
        assert!(!state.clipboard_status.contains("text payload"));
    }

    #[test]
    fn clipboard_toggle_is_session_scoped_and_updates_the_command() {
        let mut state = model();
        assert!(state.core.clipboard_session_active);
        assert_eq!(
            state.reduce_action(UserAction::ToggleClipboardSync),
            vec![UiCommand::SetClipboardEnabled(true)]
        );
        assert!(state.core.clipboard_sync_enabled);
        assert_eq!(
            state.reduce_action(UserAction::ToggleClipboardSync),
            vec![UiCommand::SetClipboardEnabled(false)]
        );

        state.core.clipboard_session_active = false;
        assert!(state
            .reduce_action(UserAction::ToggleClipboardSync)
            .is_empty());
    }

    #[test]
    fn stale_stream_events_from_another_device_do_not_replace_the_selected_session() {
        let mut state = model();
        let selected = state.core.selected_device.clone().expect("selected device");
        let inactive = state
            .core
            .devices
            .iter()
            .find(|device| device.id != selected)
            .expect("inactive device")
            .id
            .clone();
        let display = state
            .core
            .devices
            .iter()
            .find(|device| device.id == inactive)
            .and_then(|device| device.displays.first())
            .expect("display")
            .id;
        let dimensions = state.stream_dimensions;
        let overlay = state.overlay.clone();
        state.apply_event(CoreEvent::StreamStarted {
            device_id: inactive.clone(),
            display_id: display,
            width: 854,
            height: 480,
            fps: 30,
        });
        state.apply_event(CoreEvent::StreamReset {
            device_id: inactive.clone(),
            epoch: 99,
            width: 640,
            height: 360,
        });
        state.apply_event(CoreEvent::DecoderReady {
            device_id: inactive.clone(),
        });
        state.apply_event(CoreEvent::SessionEnded {
            device_id: Some(inactive.clone()),
            reason: SessionEndReason::RemoteClosed,
        });
        state.apply_event(CoreEvent::VideoUnavailable {
            device_id: inactive,
        });
        assert_eq!(state.core.selected_device, Some(selected));
        assert_eq!(state.stream_dimensions, dimensions);
        assert_eq!(state.overlay, overlay);
    }

    #[test]
    fn removing_the_selected_display_clears_selection_and_shows_an_error_overlay() {
        let mut state = model();
        let device_id = state
            .core
            .selected_device
            .clone()
            .expect("fake selected device");
        let topology =
            racc_core::Topology::new(2, Vec::new(), None).expect("empty replacement topology");
        state.apply_event(CoreEvent::TopologyChanged {
            device_id,
            topology,
        });
        assert_eq!(state.core.selected_display, None);
        assert!(matches!(&state.overlay, SessionOverlay::Error(_)));
    }

    #[test]
    fn first_topology_selects_primary_without_reporting_a_removed_display() {
        let mut state = model();
        let device_id = state
            .core
            .selected_device
            .clone()
            .expect("fake selected device");
        state.core.selected_display = None;
        state.overlay = SessionOverlay::Connecting;
        let primary_id = racc_core::DisplayId::new(77).expect("valid display id");
        let topology = racc_core::Topology::new(
            2,
            vec![Display::new(
                primary_id,
                "Primary",
                0,
                0,
                1920,
                1080,
                1000,
                60_000,
                DisplayFlags::new(true, true, true, false),
            )],
            None,
        )
        .expect("valid primary display topology");

        state.apply_event(CoreEvent::TopologyChanged {
            device_id,
            topology,
        });

        assert_eq!(state.core.selected_display, Some(primary_id));
        assert_eq!(state.overlay, SessionOverlay::Connecting);
    }
    #[test]
    fn viewer_connected_event_populates_the_explicit_peer() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        let device_id = DeviceId::new("tailnet-100.64.0.2").expect("device id");
        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::Connected(racc_proto::HelloAck {
                protocol_version: racc_proto::PROTOCOL_VERSION,
                status: racc_proto::HelloStatus::Ok,
                device_name: "remote workstation".to_owned(),
                os: racc_proto::OsType::Windows,
                app_version: "test".to_owned(),
                codecs: 1,
                max_height: 1080,
                features: 0,
                host_cpu_cores: 8,
            }),
        );
        assert_eq!(state.core.selected_device, Some(device_id.clone()));
        assert_eq!(state.core.devices.len(), 1);
        assert_eq!(state.core.devices[0].name, "remote workstation");
        assert!(state.core.devices[0].online);
        assert!(state.core.devices[0].host_capable);
        assert_eq!(
            state.core.telemetry.session.connection_state,
            racc_telemetry::ConnectionState::Connected
        );
    }

    #[test]
    fn viewer_stream_reset_and_frame_events_update_metadata_only() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        let device_id = DeviceId::new("tailnet-100.64.0.2").expect("device id");
        state.core.selected_device = Some(device_id.clone());
        state.overlay = SessionOverlay::Switching;
        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::StreamReset(racc_proto::StreamReset {
                req_id: 0,
                epoch: 5,
                codec: racc_proto::StreamCodec::H264,
                width: 1280,
                height: 720,
                fps: 30,
                topology_rev: 2,
                display_id: 7,
                status: racc_proto::StreamStatus::Ok,
            }),
        );
        assert_eq!(state.stream_dimensions, Some((1280, 720)));
        assert_eq!(state.core.telemetry.session.epoch, 5);
        assert_eq!(state.core.selected_display, racc_core::DisplayId::new(7));
        assert_eq!(state.overlay, SessionOverlay::Switching);

        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::FrameAvailable {
                epoch: 5,
                frame_id: 41,
            },
        );
        assert_eq!(state.overlay, SessionOverlay::None);
        assert_eq!(state.core.telemetry.session.epoch, 5);
    }

    #[test]
    fn viewer_decoder_selection_updates_local_decoder_telemetry() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        let device_id = DeviceId::new("tailnet-100.64.0.2").expect("device id");
        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::DecoderSelected(
                racc_telemetry::DecoderKind::MediaFoundationSynchronousMft,
            ),
        );
        assert_eq!(
            state.core.telemetry.session.decoder,
            racc_telemetry::DecoderKind::MediaFoundationSynchronousMft
        );

        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::DecoderSelected(racc_telemetry::DecoderKind::Unknown),
        );
        assert_eq!(
            state.core.telemetry.session.decoder,
            racc_telemetry::DecoderKind::Unknown
        );
    }

    #[test]
    fn reconnecting_event_uses_the_automatic_retry_overlay() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        let device_id = DeviceId::new("tailnet-100.64.0.2").expect("device id");
        state.core.clipboard_session_active = true;
        state.core.clipboard_sync_enabled = true;
        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::Session(racc_session::SessionEvent::Reconnecting),
        );
        assert!(!state.core.clipboard_session_active);
        assert!(!state.core.clipboard_sync_enabled);
        assert_eq!(state.overlay, SessionOverlay::Reconnecting);
        assert_eq!(
            state.core.telemetry.session.connection_state,
            racc_telemetry::ConnectionState::Reconnecting
        );
    }

    #[test]
    fn viewer_host_statistics_event_updates_host_telemetry() {
        let mut state = ViewModel::new(racc_core::CoreSnapshot::default());
        let device_id = DeviceId::new("tailnet-100.64.0.2").expect("device id");
        state.apply_viewer_event(
            &device_id,
            racc_core::ViewerRuntimeEvent::HostStats(racc_proto::StatsReport {
                host_cpu_pct_x10: 237,
                capture_backend: racc_proto::CaptureBackend::Dxgi,
                encoder: racc_proto::Encoder::MediaFoundationHw,
                width: 1920,
                height: 1080,
                display_refresh_mhz: 144_000,
                target_bitrate_kbps: 7000,
                actual_bitrate_kbps: 6800,
                process_cpu_pct_x10: Some(123),
            }),
        );
        assert_eq!(state.core.telemetry.host.cpu_pct_x10, 237);
        assert_eq!(
            (
                state.core.telemetry.host.width,
                state.core.telemetry.host.height
            ),
            (1920, 1080)
        );
        assert_eq!(state.core.telemetry.host.refresh_mhz, 144_000);
    }
}
