[package]
name = "racc-decode"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
racc-proto = { path = "../proto" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58.0", features = [
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-foundation = { version = "0.3.2", default-features = false, features = ["CFDictionary", "CFNumber", "CFString", "std"] }
objc2-core-media = { version = "0.3.2", default-features = false, features = ["CMBase", "CMBlockBuffer", "CMFormatDescription", "CMSampleBuffer", "CMTime"] }
objc2-core-video = { version = "0.3.2", default-features = false, features = ["CVBase", "CVBuffer", "CVImageBuffer", "CVPixelBuffer", "CVReturn"] }
objc2-video-toolbox = { version = "0.3.2", default-features = false, features = ["VTBase", "VTDecompressionProperties", "VTDecompressionSession", "VTErrors", "VTSession", "objc2", "objc2-core-media", "objc2-core-video"] }